better-auth/better-auth

- docs/content/docs/basic-usage.mdx
Fixed a typo in the documentation where client.useSsession() was incorrectly referenced instead of client.useSession().
> docs: fix typo issue

- dev/bun/_auth.ts
- docs/content/docs/concepts/api.mdx
- packages/better-auth/src/api/index.ts
- packages/better-auth/src/api/routes/forget-password.ts
- packages/better-auth/src/api/routes/session.ts
- packages/better-auth/src/api/routes/sign-up.ts
- packages/better-auth/src/api/routes/update-user.ts
- packages/better-auth/src/api/routes/verify-email.ts
- packages/better-auth/src/plugins/magic-link/index.ts
- packages/better-auth/src/plugins/organization/organization.test.ts
- packages/better-auth/src/plugins/organization/routes/crud-invites.ts
- packages/better-auth/src/plugins/organization/routes/crud-members.ts
- packages/better-auth/src/plugins/organization/routes/crud-org.ts
- packages/better-auth/src/plugins/passkey/index.ts
- packages/better-auth/src/plugins/phone-number/index.ts
- packages/better-auth/src/plugins/two-factor/backup-codes/index.ts
- packages/better-auth/src/plugins/two-factor/index.ts
- packages/better-auth/src/plugins/two-factor/totp/index.ts
- packages/better-auth/src/plugins/two-factor/verify-middleware.ts
- studio/next-env.d.ts
This PR refactors all error-handling logic to throw an `APIError` instead of returning null and handling errors with status codes on the client side. If `APIError` is thrown on the client, it will be transformed into a proper error response. On the server, it will actually throw the error. 
closes #73
> refactor: better error handling for server side calls

- docs/content/docs/authentication/microsoft.mdx
Docs used `google` for Microsoft auth instead of `microsoft`. I have not run this code, but I am pretty sure this is a mistake :)
> Docs fix: Microsoft auth is 'microsoft', not 'google'

- docs/content/docs/installation.mdx
Fix the typo on the sample code on how to use a mongodb adapter
> docs: fix typo mongodb adapter

- packages/better-auth/package.json
- packages/better-auth/src/cli/get-config.ts
- packages/better-auth/src/cli/utils/add-svelte-kit-env-modules.ts
- pnpm-lock.yaml
This is a temporary (?) fix that resolves the `$env` modules of SvelteKit and provides the environment variables from the project's `.env` file and `process.env`, removing the need of temporarily removing the imports for these modules to be able to use the `generate` and `migrate` CLI commands.
This PR also has another small change, which adds `lib/server` to a list of possible paths of the auth config file.
> feat: resolve sveltekit $env modules, add lib/server to possible config paths

- packages/better-auth/package.json
https://www.npmjs.com/package/better-auth doesn't link to the repo since the field is missing
> chore: add repo info to `package.json`

- docs/content/docs/integrations/hono.mdx
- added guide for configuring a middleware to access `user` and `session` object in all routes to avoid using the `auth.api.getSession` everytime (this works with all type of validations also) in hono
- added guide on how to correctly configure CORS in Hono.
> docs: add middleware and cors guides for hono

- docs/content/docs/examples/svelte-kit.mdx
Minor typo fix on the svelte-kit docs example
> docs: minor typo fix 

- docs/content/docs/concepts/cookies.mdx
fix typo in cookies.mdx which said ¨expiremental¨ instead of ¨experimental¨
> docs: fix typo in cookies.mdx

- docs/content/docs/plugins/2fa.mdx
Small spelling fix in docs for 2FA from "sing-in.ts" to "sign-in.ts".
> Fix spelling of sign-in.ts in docs

- packages/better-auth/src/api/middlewares/csrf.ts
- packages/better-auth/src/api/routes/csrf.ts
Current endpoint returns a token or a token with hash (current cookie). This leads to different csrf tokens being set on the client. Also the current middleware compares the current cookie (token + hash) with only the token (or token + hash if /csrf is called separately).
This pr aims to return the correct token on every `/csrf` call and to compare the correct tokens in the middleware
> fix: csrf token verification

- README.md
Looks better for download badge: https://npm.chart.dev/better-auth?primary=neutral&gray=neutral&theme=dark
> docs: link npm downloads to npm.chart.dev

- docs/content/docs/integrations/svelte-kit.mdx
In SvelteKit, load function in `+page.ts` (which runs on the client) doesn't have access to request object. The request object is only available in the load function inside `+page.server.ts` or `+layout.server.ts` (which run on the server)
I've also added appropriate `PageServerLoad` Type instead of generic `Request` Type.
:)
> fix: Update "Getting Session on a loader" example

- docs/content/docs/plugins/admin.mdx
- packages/better-auth/src/db/internal-adapter.ts
- packages/better-auth/src/plugins/admin/index.ts
This PR is to add the option to filter the users in the function listUsers for the admin plugin.
> feat: add 'where' clause support to add filters in the list users, admin plugin

- packages/better-auth/src/client/vue.ts
When an explicit baseUrl is defined in the client like shown in the docs. The website will throw following error since it currently tries to call //session.
Error thrown:
`[nuxt] [useFetch] the request URL must not start with "//".`
This pr uses the already implemented `getBaseURL` function which is used in other api calls as well, though it will still fallback to /api/auth in edge cases.
> fix: baseUrl in vue client

- docs/content/docs/integrations/nuxt.mdx
- examples/nuxt-example/lib/auth-client.ts
- packages/better-auth/src/client/vue.ts
nuxt doesn't allow to fetch internal api using the complete url when rendering on the server.
This pr allows to still have a decoupled backend or a fullstack nuxt app.
> fix: nuxt internal fetch url

- packages/better-auth/src/client/vue.ts
fix wrong order in fetch url
/auth/api -> /api/auth
> fix: typo in api call

- docs/content/docs/concepts/api.mdx
The `headers` in the Next.js comes from `next/headers` instead of `next/server`. Here's the [doc](https://nextjs.org/docs/app/api-reference/functions/headers#headers) as a reference
> Fix Next headers import

- packages/better-auth/src/integrations/next-js.ts
For hosting outside of Vercel, the middleware origin is set to localhost. This PR uses the BETTER_AUTH_URL environment variable, with the origin as a fallback.
> fix: use better auth url in nextjs middleware

- packages/better-auth/src/plugins/jwt/index.ts
I noticed that I forgot to add the ID of the key that got used to sign the token in the header.
> Added the Key ID in the token header

- docs/content/docs/basic-usage.mdx
We need to use `await` on the `next/headers` since `headers()` returns a promise. Directly accessing it shows an error in the console.
```bash
Error: In route / a header property was accessed directly with `headers().get('cookie')`. `headers()` should be awaited before using its value. Learn more: https://nextjs.org/docs/messages/sync-dynamic-apis
```
> Use `await` in the `next/headers` to prevent errors

- docs/content/docs/installation.mdx
removed 
import { github } from "better-auth/social-providers"
from the example because its unused
> remove unused github import line

- packages/cli/src/utils/get-config.ts
- packages/cli/test/getConfig.test.ts
this pull request resolves #343 through:
 
1) calculating the resolved base url by extracting it from tsconfig and joining to the cwd that is at the root of the tsconfig file. the baseUrl is relative to the tsconfig file.
2) checking if the alias and/or alias path is of a resolver type or a direct alias to a file
3) since the alias paths is relative to the base url the resulting path is the path join of the resolvedBaseUrl and the alias path
4) ensure the full alias is used.
> enhance alias path resolution

- docs/content/docs/basic-usage.mdx
- docs/content/docs/reference/options.mdx
By default, `email.signUp` will automatically log the user in upon a successful signup. Make this known in the docs and show them that this behaviour can be changed
> [docs] Update `basic-usage.mdx`

- docs/content/docs/concepts/database.mdx
In the example given in docs the the mongo client is passed directly passed to the mongodbAdapter, which is not working it should be db from mongo client 
Reading the whole code now, willing to contribute to code as well
This got me into reading the source code to get working,
> Fixed: MongoDB Adapter Docs

- demo/nextjs/app/dashboard/user-card.tsx
- demo/nextjs/lib/auth-client.ts
- docs/content/docs/concepts/session-management.mdx
- docs/content/docs/concepts/users-accounts.mdx
- docs/content/docs/plugins/bearer.mdx
- examples/astro-example/src/components/user-card.tsx
- examples/astro-example/src/libs/auth-client.ts
- examples/nextjs-example/app/dashboard/user-card.tsx
- examples/remix-example/app/components/user-card.tsx
- packages/better-auth/src/api/routes/account.test.ts
- packages/better-auth/src/api/routes/account.ts
- packages/better-auth/src/api/routes/session.test.ts
- packages/better-auth/src/api/routes/session.ts
- packages/better-auth/src/api/routes/update-user.test.ts
- packages/better-auth/src/api/routes/update-user.ts
- packages/better-auth/src/client/config.ts
- packages/better-auth/src/client/path-to-object.ts
- packages/better-auth/src/db/db.test.ts
- packages/better-auth/src/plugins/additional-fields/additional-fields.test.ts
- packages/better-auth/src/plugins/admin/index.ts
- packages/better-auth/src/plugins/bearer/bearer.test.ts
- packages/better-auth/src/plugins/phone-number/phone-number.test.ts
- packages/better-auth/src/plugins/username/username.test.ts
The `/user` prefix in the client can lead to confusion because "user" is a term used in multiple contexts, alos it makes it difficult to destructure the client objec. To resolve this, this PR removes the `/user` prefix from the URLs. For instance, the endpoint `/user/update` will now be changed to `/update-user`.
> refactor: remove user prefix from endpoints

- docs/content/docs/integrations/next.mdx
replaced the custom file which is not present by default to make the middleware easier to set up
> docs: make middleware example copy&pasteable

- docs/content/docs/authentication/email-password.mdx
- docs/content/docs/basic-usage.mdx
- packages/better-auth/src/api/routes/sign-in.ts
- packages/better-auth/src/api/routes/sign-up.ts
redirection should be handled on the frontend by the user for endpoints that don't require a callback URL to function. This pr remove callback url from endpoints that doesn't need it
> fix: remove callback url from endpoints that doesn't necessarily need it

- docs/content/docs/reference/options.mdx
This fixes a small typo in the `options` docs
> docs: Fix typo in 'trustedOrigins' heading

- docs/content/docs/installation.mdx
This commit removes a double space in the Vanilla create client instance section of the installation page.
> docs: Remove the double space in the Vanilla create client instance on the installation page

- packages/better-auth/src/plugins/magic-link/index.ts
As of right right now, we have to do something like this:
```ts
export const auth = betterAuth({
// ...database
plugins: [
magicLink({
disableSignUp: true,
sendMagicLink: async (data: {
email: string
token: string
url: string
}) => {
const isSignedUp =
(await db.user.count({
where: {
email: data.email
}
})) > 0
if (!isSignedUp) {
throw new Error('User not found')
}
// ...send magic link to email
}
})
]
})
```
but it brings some flaws with it. We are not able to provide an accurate error message to the client, because an `INTERNAL_SERVER_ERROR` is thrown.
With the commited adjustments an `USER_NOT_FOUND` error is thrown when a user isn't registered and disableSignUp is set to true. This allows us to provide a more detailed error message to the client.
> fix: magic links sent to unregistered emails when disabled sign up

- docs/content/docs/integrations/next.mdx
In Next.js 15, header is now an `async` function, so I added `await` to integrate it according to the Next.js documentation.
Nextjs 14
Nextjs 15
> update docs - nextjs integration

- packages/better-auth/src/plugins/organization/client.ts
- packages/better-auth/src/plugins/organization/organization.ts
When using `auth.api.getFullOrganization` or `authClient.organization.getFull`, the type doesn't align with `typeof auth.$Infer.ActiveOrganization`
This PR changes the type of `image` from `string` to `string | undefined`
> fix: make image optional in organization plugin

- demo/nextjs/lib/auth.ts
- docs/components/sidebar-content.tsx
- docs/content/docs/plugins/oauth-proxy.mdx
- packages/better-auth/package.json
- packages/better-auth/src/plugins/index.ts
- packages/better-auth/src/plugins/oauth-proxy/index.ts
- packages/cli/package.json
- packages/expo/package.json
A proxy plugin, that allows you to proxy OAuth requests. Useful for development and preview deployments where the redirect URL can't be known in advance to add to the OAuth provider.
> feat: oAuth proxy plugin

- packages/better-auth/src/api/index.ts
Fixes #395 
The response type coming back from `plugin.onRequest(req, ctx)` is 
```ts
const response: void | {
response: Response;
} | {
request: Request;
}
```
I suspect that because of that union type, we were returning `response` although it is not an actual Fetch Response. For this reason, the request was actually not interrupted.
This fix is a pretty simple solution, I also considered using a type guard, let me know what you think :) 
```ts
function hasResponseInterruptor(response: void | { response: Response } | { request: Request }): response is { response: Response } {
return response !== undefined && typeof response === 'object' && 'response' in response;
}
```
> fix: onRequest callback not interrupting requests

- docs/content/docs/integrations/expo.mdx
This PR updates the Expo integration documentation to include important instructions for enabling social authentication using Better Auth. Specifically, it adds details on importing the client plugin from `@better-auth/expo/client` and passing it to the plugins array when initializing the auth client.
In the _"Initialize Better Auth Client"_ step:
- I added instructions to import the client plugin from `@better-auth/expo/client`.
- I included a code snippet demonstrating how to pass the plugin to the plugins array.
- I provided a concise list explaining the importance of the client plugin:
- **Social Authentication Support:** enables social auth flows by handling authorization URLs and callbacks within the Expo web browser.
- **Secure Cookie Management:** Stores cookies securely and …
> docs: improve expo doc by including Expo client plugin setup

- demo/nextjs/lib/auth.ts
- docs/content/docs/concepts/cookies.mdx
- packages/better-auth/src/cookies/index.ts
> fix: app name shouldn't be used to prefix cookies

- packages/better-auth/src/api/routes/sign-out.ts
Fix for #451
From what I can tell, this fixes the types on `signOut`
Before:
After:
Let me know if there's anything else I can add 🙂
> fix: add `requireHeaders` to sign out api

- packages/better-auth/src/plugins/organization/client.ts
Changed the URL in the client to match the endpoint in `crud-org.ts`: https://github.com/better-auth/better-auth/blob/00d36eb42482771a834f27573a55afda2f17a602/packages/better-auth/src/plugins/organization/routes/crud-org.ts#L218-L219
> Change URL of get full organization endpoint

- docs/content/docs/integrations/astro.mdx
**Title**: Fix Typo in Astro Integration Documentation Path
**Description**:  
This pull request addresses a typo in the Astro integration documentation. The current path mentioned as `page/api/auth/[...all].ts` has been corrected to `pages/api/auth/[...all].ts` to align with the standard directory structure.
This change ensures that users following the documentation will have accurate instructions, preventing potential confusion during setup.
**Linked Issue**:  
Closes #488
> docs: fix astro pages path

- docs/content/docs/concepts/database.mdx
This pull request includes a change to the `secondaryStorage` configuration in the `database.mdx` file to ensure that values are stored as JSON strings in Redis.
```
const sessionStringified = await secondaryStorage.get(sessionId);
if (sessionStringified) {
const s = JSON.parse(sessionStringified);
```
* [`docs/content/docs/concepts/database.mdx`](diffhunk://#diff-3fb82b9771e62eb4c129ceb5109e4500f630d5fd40b289d06ff38f69d4c52dc3L253-R254): Modified the `set` method in `secondaryStorage` to store values as JSON strings in Redis.
> docs: redis value change

- packages/better-auth/src/types/helper.ts
- packages/better-auth/src/types/options.ts
Adapters currently do not support custom id column name
> fix: omit id in custom column names

- packages/better-auth/src/init.ts
Corrected the parameter order for the verify method: Updated the verify function to accept password as the first argument and hash as the second argument.
// BetterAuthOptions types
```js 
password: {
...
verify?: (password: string, hash: string) => Promise<boolean>;
```
// verifyPassword function
```js
export const verifyPassword = async (hash: string, password: string) => {...}
```
> fix: correct parameter order for password verification method

- docs/content/docs/integrations/nuxt.mdx
- docs/content/docs/plugins/organization.mdx
- packages/better-auth/src/social-providers/index.ts
I have bad DX on webstorm with old behavior. I think it's too much infer here that delays ts server
old behavior:
new behavior:
> feat: improve type hinting for social providers

- packages/cli/src/commands/generate.ts
`@better-auth/cli generate -y` doesn't work, this is a fix & matching `--y` flag like the `@better-auth/cli migrate --y`
> fix(cli): fix -y flag in generate.ts

- packages/better-auth/src/plugins/generic-oauth/index.ts
It is possible that the idToken does not contain the required id or data, so it is better to unify and destructure the information; this resolves the error when accountLinking is enabled
> fix: id is not a property in idToken payload when accountLinked is enabled

- packages/cli/src/generators/drizzle.ts
Providing a custom model name results in errors as the `references` uses the custom model name, but the actual model definition does not. The drizzle adapter also looks up the custom model name when forming queries, which would also currently not find the model correctly.
> fix: Drizzle schema generation custom model name

- packages/better-auth/src/plugins/admin/index.ts
Updates `banExpires` field type in `UserWithRole` to `Date` to reflect the database type
> fix: update admin plugin UserWithRole type to reflect db schema

- packages/better-auth/src/adapters/drizzle-adapter/drizzle-adapter.ts
- packages/better-auth/src/adapters/drizzle-adapter/test/adapter.drizzle.test.ts
- packages/better-auth/src/adapters/kysely-adapter/kysely-adapter.ts
- packages/better-auth/src/adapters/kysely-adapter/test/adapter.kysley.test.ts
- packages/better-auth/src/adapters/memory-adapter/memory-adapter.ts
- packages/better-auth/src/adapters/memory-adapter/memory.test.ts
- packages/better-auth/src/adapters/mongodb-adapter/adapter.mongo-db.test.ts
- packages/better-auth/src/adapters/prisma-adapter/prisma-adapter.ts
- packages/better-auth/src/adapters/prisma-adapter/test/adapter.prisma.test.ts
- packages/better-auth/src/adapters/test.ts
This PR resolves an issue where the `generateId` function was not called consistently, specifically when a model `id` was already provided to the adapter. You can reproduce the issue using the `/organization/create` API endpoint.
> fix: always prefer custom generateId function

- packages/cli/src/generators/drizzle.ts
Using the `usePlural` option in the Drizzle adapter options does not affect the behaviour of the `generate` CLI command.
This PR addresses this and makes the CLI command pluralize the generated model names when the `usePlural` option is `true`.
> feat(cli): account for usePlural option in drizzle schema generation

- docs/content/docs/basic-usage.mdx
Fix typos "realted" to "related" and "functionilty" to "functionality" in basic-usage.mdx.
> docs: fix typos in basic-usage.mdx

- docs/content/docs/concepts/session-management.mdx
Corrected "retunr" to "return" in the customSession function to fix the typo
> Fix typo: "retunr" to "return" in customSession

- packages/better-auth/src/plugins/admin/index.ts
> fix: missing export type for admin plugin

- packages/expo/src/client.ts
- **`Constants.platform?.scheme`** when working with platform-specific functionality or debugging native builds.
- **`Constants.expoConfig?.scheme`** for a simpler, cross-platform approach during development or managed workflows.
If the app has not been ejected, `Constants.expoConfig?.scheme` will generally be sufficient.
> fix: get scheme from expo config

- docs/content/docs/plugins/2fa.mdx
- packages/better-auth/src/plugins/two-factor/otp/index.ts
- packages/better-auth/src/plugins/two-factor/totp/index.ts
This pull request closes #653 . It adds the option, to make the digit length of otp configurable.
> feat: add support for configurable digits length

- docs/content/docs/authentication/twitter.mdx
- packages/better-auth/src/social-providers/twitter.ts
- The Twitter v2 API does not return the `email` field.
- However, the `getUserInfo` function in `/social-providers/twitter` expects an `email` value.
- This causes a sign-in failure with the error: `email_not_found` when using Twitter OAuth.
- Replaced the usage of the `email` field with the `username` value returned by the Twitter API.
- Adjusted the `getUserInfo` function to handle this change.
- Twitter OAuth now functions correctly without triggering the `email_not_found` error.
- Fixes #591
> Fix "email not found" Error in Twitter OAuth

- docs/content/docs/integrations/expo.mdx
changes 
plugins: [
expo
]
to 
plugins: [
expo()
]
> chore: typo in expo docs change plugins expo to expo() 

- packages/better-auth/src/plugins/generic-oauth/index.ts
Fixed an issue in the Generic OAuth plugin where refreshToken, idToken, and accessTokenExpiresAt were not being saved.
> fix: save refreshToken in generic-oauth plugin

- packages/better-auth/src/social-providers/discord.ts
closes #739 
adds a consent option to Discord, defaulting to none as suggested in the linked issue.
> feat(discord): add consent as an option

- packages/better-auth/src/types/options.ts
> fix: allow trusted providers to accept a string value for generic OAuth

- docs/content/docs/plugins/passkey.mdx
Changed the name of the column at passkey plugin from WebAuthnUserId to webauthnUserID
> fix:changed the name of column webauthnUserID

- docs/content/docs/concepts/plugins.mdx
- Made sure the reader knows the ID can be the same for both server & client plugins.
- Added demo code to show the creation of both the server & the client plugins.
- Made the `myPlugin` and `myClientPlugin` have an `export`. An opinionated default.
- The heading "When to use Middleware, Hooks, On Request, On Response" was removed:
- That heading was written after the doucmentation of middleware, hooks, on request, etc. Most people skim the docs to find what they want, to read all of that code not knowing what each function does, makes it harder for them to get to the end and finally read that heading which provides more context.
- I added a new heading, which is above middleware, hooks, etc and that explains each primary function and when you would use them.
- Fixed the client's …
> Docs/concept/plugin refactor 

- docs/content/docs/examples/next-js.mdx
The link for the next js example in the docs was incorrect. Added the updated link.
> docs(fix): provided updated link for next js example

- docs/components/landing/hero.tsx
Very small change to disable select for "git:(main) x" in hero. This is useful in order to avoid people copying the "git:(main) x" part and getting an error
> Disable select for "git:(main) x" in hero

- packages/better-auth/src/api/routes/update-user.ts
Due to a `!name`, the following code wouldn't work:
```ts
await auth.api.updateUser({
body: {
name: ''
},
headers: await headers()
});
```
> fix: Allow empty name in updateUser

- packages/better-auth/src/api/routes/email-verification.ts
When changing an email, `emailVerified` is not updated to false when the new email is set.
> fix: Set emailVerified to false when changing email

- docs/content/docs/guides/your-first-plugin.mdx
- docs/content/docs/plugins/email-otp.mdx
- packages/better-auth/src/plugins/email-otp/index.ts
This PR includes improvements for the Email OTP plugin:
- Consistently return errors with values from `ERROR_CODES`.
- Consistently return `OTP_EXPIRED` when the OTP has expired.
- Add details about password reset via OTP to docs.
It also includes a fix for the 'your first plugin' guide (`throw APIError` -> `throw new APIError`).
> fix: email OTP error codes and docs

- docs/content/docs/integrations/nuxt.mdx
Added an example to get the session on a server route. When implementing this I looked at the other integrations to see how it worked.
> docs: add Nuxt server API route getSession example

- docs/content/docs/plugins/magic-link.mdx
Fixed invalid typescript annotation in demo code for magic link plugin.
> docs: fix invalid typescript in magic-link docs

- docs/content/docs/concepts/database.mdx
Redis client needs to connect before use, and the stored stringified JSON needs to be parsed before return
> docs: fix redis example for secondaryStorage

- packages/better-auth/src/adapters/prisma-adapter/prisma-adapter.ts
This change exports the PrismaConfig interface from the Prisma adapter to fix errors related to creating declarations with tsc.
fixes #899
> Export PrismaConfig Interface

- packages/better-auth/src/social-providers/apple.ts
The `options.redirectURI` should be prioritized, only the Apple provider has this bug.
> fix: apple redirect uri

- packages/cli/src/utils/get-config.ts
I'm using sveltekit and I wanted to put my `auth.ts` file in `lib/server` to follow [sveltekit's project structure](https://svelte.dev/docs/kit/project-structure) and better auth did not know where the config was anymore.
Found out this is most likely a typo in the get config file, just missing slashes.
> fix: get-config paths for sveltekit or similar

- docs/app/docs/[[...slug]]/page.tsx
This pull request includes a small but important change to the `docs/app/docs/[[...slug]]/page.tsx` file. The change enables the footer and add some margin to the bottom to make it look nicer
Changes in `page.tsx`:
* Enabled the footer and added a component to it. ([docs/app/docs/[[...slug]]/page.tsxL49-R50](diffhunk://#diff-bd8138eb3a2a89f261dfd07ac6032ea5d5b9cacd694bf167a6577cf5135b7a8eL49-R50))
> docs: add spacing at the bottom of the document

- packages/better-auth/src/plugins/email-otp/email-otp.test.ts
- packages/better-auth/src/plugins/email-otp/index.ts
> fix: email OTP during signup fails to send when email verification is required

- docs/content/docs/authentication/apple.mdx
- packages/better-auth/src/social-providers/apple.ts
> The main thing that tripped me up, is that better-auth requires clientId and clientSecret on socialProviders.apple in config -> this is where you're place the service id and jwt secret generated from p8-file for "Sign-in with Apple" on web.
However on native iOS, it doesn't use the service id but the app id (bundle id) as client id, so if using the service id as clientId in signIn.social() with idToken, it throws an error: JWTClaimValidationFailed: unexpected "aud" claim value.
> For iOS native "SignIn with Apple" with idToken, it expects the app/bundle id as clientId and doesn't require the clientSecret.
https://github.com/better-auth/better-auth/issues/421#issuecomment-2466911181
The return value of the `decodeJwt` function is already the payload
> fix: sign In with Apple With ID Token not work

- docs/content/docs/basic-usage.mdx
- docs/content/docs/installation.mdx
- docs/content/docs/integrations/tanstack.mdx
- examples/tanstack-example/app/routes/api/auth/$.ts
- packages/cli/test/__snapshots__/auth-schema.txt
Unsure when exactly this was changed, but it was changed at some point and also updated in the tanstack docs over here three weeks ago: https://github.com/TanStack/router/commit/2cf38ac6fe3e74784f9b8289b9fd3202a3011a75
> fix(docs): use `APIRoute` instead of `Route` for tanstack start api routes

- packages/better-auth/src/api/call.test.ts
- packages/better-auth/src/api/routes/email-verification.ts
- packages/better-auth/src/api/routes/sign-in.ts
- packages/better-auth/src/api/routes/sign-up.test.ts
- packages/better-auth/src/api/routes/sign-up.ts
- packages/better-auth/src/api/routes/update-user.test.ts
- packages/better-auth/src/api/routes/update-user.ts
- packages/better-auth/src/db/db.test.ts
- packages/better-auth/src/plugins/admin/admin.test.ts
- packages/better-auth/src/plugins/anonymous/index.ts
- packages/better-auth/src/plugins/email-otp/email-otp.test.ts
- packages/better-auth/src/plugins/email-otp/index.ts
- packages/better-auth/src/plugins/magic-link/index.ts
- packages/better-auth/src/plugins/magic-link/magic-link.test.ts
- packages/better-auth/src/plugins/multi-session/index.ts
- packages/better-auth/src/plugins/one-tap/index.ts
- packages/better-auth/src/plugins/organization/organization.test.ts
- packages/better-auth/src/plugins/phone-number/index.ts
- packages/better-auth/src/plugins/phone-number/phone-number.test.ts
- packages/better-auth/src/plugins/two-factor/two-factor.test.ts
- packages/better-auth/src/plugins/two-factor/verify-middleware.ts
- packages/better-auth/src/plugins/username/index.ts
- packages/better-auth/src/plugins/username/username.test.ts
- packages/better-auth/src/test-utils/test-instance.ts
- packages/cli/test/migrate.test.ts
This PR standardizes how endpoints return user and session-related data. All endpoints, except `/get-session`, now return a `token` if a new one is generated, and `status: true` for updates and related calls.
> refactor: standardize how session and user data is returend in endpoints

- docs/content/docs/concepts/hooks.mdx
- add the import `createAuthMiddleware` where the entire auth.ts is shown as example
- change `ctx.response.headers.set` to `ctx.responseHeader.set`, as former is not correct
> fix(docs): improve the hooks section

- docs/content/docs/plugins/phone-number.mdx
Just fixed a small typo from the docs: "remeberMe" -> "rememberMe"
PS: Thanks for Better Auth btw, it's so good! Keep up the great work 🙌
> docs: Fix minor typo

- packages/better-auth/src/api/routes/email-verification.ts
- packages/better-auth/src/plugins/magic-link/index.ts
> fix: create a new session on email verification if current session email doesn't match

- packages/better-auth/src/client/plugins/index.ts
Simple fix to remove duplicate line
`export * from "../../plugins/passkey/client";`
> chore: remove duplicate passkey export

- docs/content/docs/integrations/node.mdx
A few people on the team fell for this trick, I added an extra Warn before installing it. 
thx https://github.com/better-auth/better-auth/issues/320
> docs: add warn for node `express.json()` before install

- packages/better-auth/src/plugins/passkey/index.ts
> fix: user verification shouldn't be required when passkey registration

- packages/better-auth/src/api/routes/email-verification.ts
- packages/better-auth/src/api/routes/sign-in.ts
- packages/better-auth/src/api/routes/sign-up.ts
- packages/better-auth/src/api/routes/update-user.ts
- packages/better-auth/src/plugins/anonymous/index.ts
- packages/better-auth/src/plugins/email-otp/index.ts
- packages/better-auth/src/plugins/magic-link/index.ts
- packages/better-auth/src/plugins/one-tap/index.ts
- packages/better-auth/src/plugins/phone-number/index.ts
- packages/better-auth/src/plugins/two-factor/verify-middleware.ts
- packages/better-auth/src/plugins/username/index.ts
I propose restoring the user data in the response of api.signUpEmail to complete the registration flow in my Nest.js application. Without this change, I am restricted to using versions of better-auth prior to v1.0.23.
The issue I am facing is described in #1036. Importantly, this modification does not break any existing functionality. Notably, the api.signInEmail endpoint already includes the user data in its response (which seems to be an oversight).
I kindly request that this PR be merged as a temporary measure.
> feat: restore the user data in the response

- packages/better-auth/src/plugins/email-otp/email-otp.test.ts
- packages/better-auth/src/plugins/email-otp/index.ts
when disableSignUp and user not found, should not create and send verification OTP.
> fix(emailOtp): do not create verification when disableSignUp

- packages/better-auth/src/social-providers/google.ts
The google-client has some missing params ('display' and 'hd')
google docs: https://developers.google.com/identity/openid-connect/openid-connect#hd-param
closes #1041
> fix: add missing google auth uri params

- packages/better-auth/src/plugins/organization/organization.test.ts
- packages/better-auth/src/plugins/organization/routes/crud-invites.ts
Via the commit https://github.com/better-auth/better-auth/commit/6ab16893 a new check was introduced, with the goal to limit the assignment of the "creator" role during the sending of an invitation, so that only other users holding the "creator" role can invite new users and assign them the "creator role" as part of this invitation.
There are two conditions involved in this check:
1. Does the user sending the invite have the "creator" role, and
1. is the role, that is to be assigned to the new user, the "creator" role
These however are combined with an OR operator, instead of an AND.
This introduced two issues:
1. Invites can only be sent by users holding the creator role, other roles can no longer send any invites, even when they have the correct permissions, and
1. the "creator" role …
> fix(organization): limit creator role invites to users with same role

- docs/content/docs/reference/faq.mdx
Remove the info about declarations being `false` in tsconfig.
And also updated the info on `strict`
> fix(docs): FAQ page - ts errors had outdated information

- packages/better-auth/src/api/routes/email-verification.ts
- packages/better-auth/src/api/routes/sign-in.ts
- packages/better-auth/src/api/routes/sign-up.ts
- packages/better-auth/src/api/routes/update-user.ts
- packages/better-auth/src/oauth2/link-account.ts
- packages/better-auth/src/types/options.ts
This adds the possibility to set an expiration time (in seconds) for the verification mail.
I left it a 3600s as default, but you can add any time.
Example:
```typescript
emailVerification: {
expiresIn: 7200, // 2 hours
sendVerificationEmail: async ({ user, url, token }, request) => {
// Send the email verification email
},
}
```
> Add expiresIn for email verification

- packages/better-auth/src/plugins/generic-oauth/index.ts
Various oauth providers support custom parameters as part of their `authorization_endpoint` url. This allows users of the `genericOAuth` plugin to provide those custom parameters.
closes #1064
> feat: support overwriting auth-url params in the generic-oauth plugin

- docs/content/docs/concepts/plugins.mdx
> fix(docs): code highlight typo

- packages/better-auth/src/types/adapter.ts
* Extracted the types out so that devs who are creating adapters can infer the type
* renamed `filename` to path as some database libraries require the file to be in a specific location.
* For example with the Convex DB, the schema MUST be in the `/convex/schema.ts` file.
* By using `path`, and setting the dev's project directory as a base, devs can pass relative pathnames including the file name & extension to explicitly define the schema file creation location
* added JSDoc to each property
> refactor: Adapter createSchema return type

- docs/content/docs/authentication/email-password.mdx
The docs show the default maxPasswordLength to be 32, when it is 128.
> Fix docs default maxPasswordLength

- packages/better-auth/src/plugins/jwt/index.ts
fix: add missing algorithm parameter in importJWK function
- Add explicit algorithm parameter when importing private key using importJWK
- Resolve "'alg' argument is required when 'jwk.alg' is not present" error in Bun environment
- Default to 'EdDSA' if no algorithm is specified in keyPairConfig
This change ensures compatibility with stricter JWT implementations and fixes
the token generation process in Bun runtime.
> Fix JWT private key import by explicitly specifying algorithm

- packages/better-auth/src/plugins/organization/routes/crud-org.ts
This PR adds membership validation to the `getFullOrganization` endpoint by checking if the requesting user is a member of the specified organization. This change enhances security by ensuring that only authorized users can access the organization's details.
Reused isMember check from `setActiveOrganization`
closes #1165
> feat: Add Membership Validation to getFullOrganization Endpoint closes #1165

- docs/content/docs/concepts/client.mdx
This pull request includes a small change to the `docs/content/docs/concepts/client.mdx` file. The change corrects a typo in the example code by modifying `returns` to `return` to ensure proper syntax.
> docs: fix typo

- packages/better-auth/src/types/adapter.ts
Changed:
"Relative paths are supported, with the current working directory devs as the base."
To:
"Relative paths are supported, with the current working directory of the developer's project as the base."
This also means the CLI which generates schemas must also identify the projects package.json and use that as a reference for the base directory.
> fix: typo on JSDoc

- packages/better-auth/src/api/rate-limiter/index.ts
- packages/better-auth/src/db/field.ts
- packages/better-auth/src/db/get-migration.ts
- packages/better-auth/src/db/get-tables.ts
closes #1190   closes #1154
lastRequest column on rate limit table was using int4 since we stored timestamp in ms it was way over int4 limit so we need to change it to int8. This is the only table in better auth package that has number in schema, so for now this fix should be okay but i can take a look and implement more customizable approach for database types so in future for example all fields that have type of number won't use int8 but instead specified by schema/options
> fix: fixed number mapping for rate limit migration

- packages/better-auth/src/adapters/drizzle-adapter/test/schema.ts
I noticed a user in the BetterAuth Discord server who was reading this file as a reference to creating their schema. This schema file has inaccurate values, but was specifically designed for unit-testing. I added comments at the top to state this.
> chore: added comments to schema unit test code

- docs/content/docs/authentication/microsoft.mdx
- packages/better-auth/src/oauth2/create-authorization-url.ts
- packages/better-auth/src/social-providers/microsoft-entra-id.ts
Adds a `requireSelectAccount` option to Microsoft Entra ID so that when `true` even if the user is logged in with only one Microsoft account they have to choose their account. Defaults to `false`.
Closes #1209
> feat: support Microsoft Entra ID select_account prompt

- docs/content/docs/concepts/users-accounts.mdx
I made a small fix in the docs to emphasize that the change verification email must be sent to the current user email address, not to the new email. 
P.S. Thanks for the beautiful and useful auth library. I am integrating it on a real production project and soon will write a post about it. I migrated from NextAuth.js (v4).
> [docs] Change email verification must be sent to the current user email 

- packages/cli/src/generators/drizzle.ts
- packages/cli/src/generators/prisma.ts
This pull request adds logic to the schema generators for both Drizzle and Prisma to handle `bigint` fields appropriately.
Closes #1216
Updates to Drizzle schema generation:
* [`packages/cli/src/generators/drizzle.ts`](diffhunk://#diff-08d92411458f1a542439c00e1269f9c43f2e69d6cdbaeb9d5d205c6c092bf9e6R21-R28): Added logic to check for `bigint` fields and update the import statements to include `bigint` if necessary.
* [`packages/cli/src/generators/drizzle.ts`](diffhunk://#diff-08d92411458f1a542439c00e1269f9c43f2e69d6cdbaeb9d5d205c6c092bf9e6L52-R59): Modified the schema generation logic to use `bigint` for PostgreSQL and MySQL when a field is marked as `bigint`.
Updates to Prisma schema generation:
* [`packages/cli/src/generators/prisma.ts`](diffhunk://#diff-b32e8aeb98c8b8239920a352c8ca1f870e …
> fix(cli): add bigint type to generators

- packages/better-auth/src/api/rate-limiter/index.ts
This pull request includes a change to the `createDBStorage` function in the `packages/better-auth/src/api/rate-limiter/index.ts` file. The change ensures that the `lastRequest` field returned from db is converted from a `bigint` to a `number` before use in TypeScript.
Closes #1231
* [`packages/better-auth/src/api/rate-limiter/index.ts`](diffhunk://#diff-266a45270a21e4b11dcd53ed439c47158c823a5305a589055fa2307f5a543d44R47-R51): Added a check to convert `lastRequest` from `bigint` to `number` if necessary.
> fix(rate-limiter): convert bigint lastRequest to number

- docs/components/blocks/features.tsx
- docs/components/sidebar-content.tsx
Minor fixes svg props name & key warnings in local documentation.
> fix(docs): prop names and react key warnings

- docs/app/docs/[[...slug]]/page.tsx
It breaks because the next/prev page is a group, not a usual page.
> fix(docs): navigation buttons not showing due to groups

- docs/components/builder/social-provider.tsx
Currently, BetterAuth's social provider supports `twitter` instead of `x`. The Better Auth home page code builder generates `x`, which is incorrect. This is fixed.
> fix: home-page builder using `twitter` instead of `x`

- packages/better-auth/src/api/routes/sign-in.ts
> fix: ensure correct status code for unverified email in sign-in

- packages/expo/src/client.ts
- packages/expo/src/expo.test.ts
In cases where the session_data cookie is expired, but session_token is not, the server returns only a newly signed session_data. 
The current implementation causes the existing session_token to be erased, causing a log-out. 
This commit fixes it, along with test cases to verify.
> Bugfix: Expo client with cookieCache enabled.

- packages/better-auth/src/plugins/admin/index.ts
- packages/better-auth/src/plugins/email-otp/index.ts
- packages/better-auth/src/plugins/phone-number/index.ts
Plugins are currently inconsistently exporting their options. Most are... but a few don't. I'm using this in my code.
This PR adds exports for:
- PhoneNumberOptions
- AdminOptions
- EmailOTPOptions
> fix: Make plugin options type exports consistent

- packages/better-auth/src/oauth2/validate-authorization-code.ts
- packages/better-auth/src/plugins/generic-oauth/index.ts
- packages/better-auth/src/social-providers/apple.ts
- packages/better-auth/src/social-providers/discord.ts
- packages/better-auth/src/social-providers/dropbox.ts
- packages/better-auth/src/social-providers/facebook.ts
- packages/better-auth/src/social-providers/github.ts
- packages/better-auth/src/social-providers/gitlab.ts
- packages/better-auth/src/social-providers/google.ts
- packages/better-auth/src/social-providers/linkedin.ts
- packages/better-auth/src/social-providers/microsoft-entra-id.ts
- packages/better-auth/src/social-providers/spotify.ts
- packages/better-auth/src/social-providers/twitch.ts
- packages/better-auth/src/social-providers/twitter.ts
In some places in the codebase we allow the user to override the redirect URI. Sometimes this is respected and sometimes it is not. This change ensures that we handle it consistently, and that it is respected in the generic oauth plugin.
My concrete use case was setting up oauth proxy (the plugin didn't quite fit my use-case) and my generic oauth provider was not behaving.
> Use redirect URI from options rather than manually overriding

- packages/better-auth/src/plugins/bearer/index.ts
> Fix (bearer): 'set-auth-token' header not exposed with CORS (#917)

- docs/content/docs/plugins/oauth-proxy.mdx
docs mention redirectURL in both socialProviders option and authClient.signIn.social call which don't exist.
Fixing this by using redirectURI for socialProviders and callbackURL for client signIn which both works well for me
> fix oauth-proxy docs - redirectURL

- docs/app/docs/[[...slug]]/page.tsx
> fix(docs): page navigation buttons don't work if the next/prev category's index[0] is a group

- packages/better-auth/src/adapters/drizzle-adapter/drizzle-adapter.ts
`getSchema` already calls `getModelName`. When custom tables are used, this results in a bug where better-auth can't find the table name:
```
TypeError: undefined is not an object
```
This PR fixes the incorrect call to `getModelName`.
> Fix incorrect call to `getModelName`

- docs/content/docs/plugins/organization.mdx
Adds a missing required field to the invitation schema on docs.
Before:
After:
> docs(fix): add `inviterId` field to invitation schema

- docs/content/docs/integrations/hono.mdx
Caused by c26285b238b84215665729f47257b0d6dc9b6aec
The pattern should be `*` instead of `**` since it's not a supported syntax
It is causing strange issue then in the Hono server handlers
**Working version**
```ts
const app = new Hono()
const userRoute = new Hono()
// .get("/top", (c) => {
//   return c.json({ message: "Top" }, 200)
// })
.get(
"/:id",
zValidator(
"param",
z.object({
id: z.string(),
})
),
(c) => {
return c.json({ message: `Hello ${c.req.param("id")}` }, 200)
}
)
const routes = app.route("/user", userRoute)
app.on(["POST", "GET"], "/api/auth/**", (c) => {
return c.json({ message: "Hello" }, 200)
})
export default app
// curl http://localhost:3000/api/auth/ok 
// {"message":"Hello"}
```
**Non working version**
```tsx
const userRoute = new Hono()
.get("/top", (c) => {
return …
```
> docs: wrong pattern in hono integration code

- docs/content/docs/authentication/email-password.mdx
The docs said "OWSAP" instead of "OWASP"
> Fix OWSAP typo

- docs/content/docs/plugins/phone-number.mdx
- docs/content/docs/reference/faq.mdx
Bello! I was reading through the docs and just noticed some small typos or grammar errors here or there, and took it upon myself to fix everything up! All changes are listed below!
- "middelware" → "middleware" (`docs/content/docs/reference/faq.mdx`)
- "reqiures" → "requires" (`docs/content/docs/plugins/phone-number.mdx`)
- "//optionally you can alos pass `getTempName` function to generate a temporary name for the user" → "//optionally, you can also pass `getTempName` function to generate a temporary name for the user" (`docs/content/docs/plugins/phone-number.mdx`)
- "//by default it will use the phone number as the name" → "//by default, it will use the phone number as the name" (`docs/content/docs/plugins/phone-number.mdx`)
> docs: Minor grammar and spelling fixes

- packages/better-auth/src/social-providers/google.ts
"The value of iss in the ID token is equal to accounts.google.com or https://accounts.google.com."
Source: https://developers.google.com/identity/gsi/web/guides/verify-google-id-token
I ran into this when trying to auth via idToken obtained from auth within a Chrome Extension. According to the Google doc above the iss can also be "accounts.google.com", which was the case for the idToken I got.
> 🐛 Fix Google IdToken Auth

- docs/content/docs/integrations/nuxt.mdx
When using `useFetch` it needs an await attribute to be properly used, this will allow the authClient to function.
> fix(docs): Nuxt integration with useFetch

- docs/content/docs/guides/next-auth-migration-guide.mdx
Documentation was pointing to the outdated url: betterauth.com
> Fixed broken hyperlink to betterauth.com

- packages/cli/src/generators/kysely.ts
Change kysely generate schema file name confirmation based on output option
Previously if we fill the `--output` option, we still got a confirmation message with the better auth default file name instead of the `--output` that we input before.
Closes #1268
> fix(cli): wrong kysely schema filename

- docs/content/docs/integrations/svelte-kit.mdx
add an example for loading user session in a .server.ts file without sveltekit being where the instance is hosted ( via the client )
> add example

- docs/content/docs/concepts/database.mdx
This pull request includes a minor change to the `docs/content/docs/concepts/database.mdx` file. The change corrects a syntax error by replacing a comma with a semicolon in the `delete` method of the `betterAuth` configuration.
* [`docs/content/docs/concepts/database.mdx`](diffhunk://#diff-3fb82b9771e62eb4c129ceb5109e4500f630d5fd40b289d06ff38f69d4c52dc3L246-R246): Corrected a syntax error in the `delete` method by replacing a comma with a semicolon.
> docs: fix syntax error

- docs/content/docs/integrations/hono.mdx
With Hono `/api/auth/*` will cover everything that comes below that path.
There is no `**` in Hono, `*` works just fine.
> fix(docs): fix routes in hono integration example code

- docs/components/sidebar-content.tsx
- docs/content/docs/plugins/admin.mdx
- packages/better-auth/src/__snapshots__/init.test.ts.snap
- packages/better-auth/src/adapters/drizzle-adapter/drizzle-adapter.ts
- packages/better-auth/src/adapters/kysely-adapter/kysely-adapter.ts
- packages/better-auth/src/adapters/memory-adapter/memory-adapter.ts
- packages/better-auth/src/adapters/mongodb-adapter/mongodb-adapter.ts
- packages/better-auth/src/adapters/prisma-adapter/prisma-adapter.ts
- packages/better-auth/src/db/internal-adapter.ts
- packages/better-auth/src/plugins/admin/admin.test.ts
- packages/better-auth/src/plugins/admin/index.ts
- packages/better-auth/src/types/adapter.ts
closes #1222 and various feature requests in the discord.
This feature will return the total amount of users as well as the limit and offset that were used for the list-users search. This will allow you to do proper pagination without requiring additional API calls.
Types:
```
{
users: [User],
total: number,
limit: number | undefined
offset: number | undefined
}
```
I purposefully made `limit` and `offset` be undefined when they aren't queried. This way you can easily check if a limit or offset were used or not. If making them undefined is undesirable I can always change them to, for example, -1.
Example response:
```json
{
"users": [
{
"id": "678faf201d309d6892b774c0",
"name": "d3vision",
"email": "info@d3vision.dev",
"emailVerified": true,
"image": …
```
> feat: add total users table/collection count to admin plugin list-users endpoint

- packages/better-auth/src/plugins/open-api/generator.ts
node path use colon(:) as parameter but openAPI use curly brackets({})
/reset-password/:token -> /reset-password/{token}
> FIX: Wrong generated openAPI path format

- packages/better-auth/src/plugins/oidc-provider/index.ts
- packages/better-auth/src/plugins/oidc-provider/types.ts
The `userinfo_endpoint` key in an oidc discovery endpoint should be lowercase snake_case.
When using better-auth with the DotNET OIDC library it was throwing an error when it was unable to find the user info endpoint: https://learn.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.protocols.openidconnect.openidconnectconfiguration.userinfoendpoint?view=msal-web-dotnet-latest#microsoft-identitymodel-protocols-openidconnect-openidconnectconfiguration-userinfoendpoint
Reference: https://swagger.io/docs/specification/v3_0/authentication/openid-connect-discovery/
> fix(oidc-plugin): user info endpoint casing to match OIDC spec

- examples/astro-example/package.json
- examples/astro-example/src/auth.ts
- examples/astro-example/src/layouts/root-layout.astro
- examples/astro-example/src/pages/dashboard.astro
- examples/astro-example/src/pages/index.astro
- examples/astro-example/src/pages/sign-in.astro
- examples/astro-example/src/pages/sign-up.astro
- examples/astro-example/src/pages/two-factor.astro
- examples/astro-example/src/pages/two-factor/email.astro
- package.json
- "start" script doesn't even execute all the commands we need to start working dev server
- "astro" script is redundant with pnpm
- Missing imports
- Example doesn't work without imports
- I'm not aware of any auto-import features in Astro
- VS Code is complaining about missing imports too
- Fixed messed up indentation along the way
- Moved `<script>` tag outside the `<RootLayout>` component as per Astro convention
> Astro example: Add missing imports, remove unused scripts, fix indentation

- demo/nextjs/components/sign-up.tsx
This PR aims to fix the bug on the sign-up page of the Next JS demo. Previously the form on the sign-up page asks the user to enter their password with which they want to sign up and then re-enter the password. The issue is that the sign-up process goes through even if the user enters a different password in the 'Confirm Password' field. 
After the changes in this PR. The user will be notified with a toast which should guide them to match the passwords entered in the 'Password' and 'Confirm Password' field.
Closes #1450
> fix: Next JS demo confirm password validation

- docs/content/docs/authentication/microsoft.mdx
add a simple line to show that a tenant id can be passed optionally
> Add tenantId optional to Microsoft Social Provider example

- packages/better-auth/src/plugins/oidc-provider/index.ts
The `sub` property is missing from the /userinfo response.
`The sub (subject) Claim MUST always be returned in the UserInfo Response.`
Reference: https://openid.net/specs/openid-connect-core-1_0.html#UserInfoResponse
> fix(oidc-plugin): sub is required /userinfo response

- packages/better-auth/src/db/schema.ts
- packages/better-auth/src/plugins/jwt/index.ts
- packages/better-auth/src/plugins/oidc-provider/authorize.ts
- packages/better-auth/src/plugins/oidc-provider/index.ts
- packages/better-auth/src/plugins/oidc-provider/types.ts
- `deleteVerificationValue` was incorrectly using `code.toString()` instead of `verificationValue.id` as parameter
- Added `nonce` value to `verifications` schema to store and handle correctly as part of OIDC flow. Previously the nonce used in the `SignJWT` method was set to `body.nonce` which was undefined.
- Added `alg` property to output of `/jwks` endpoint. See #1277.
> OIDC Fixes

- packages/better-auth/src/plugins/generic-oauth/index.ts
This PR adds support to `account.accountLinking.allowDifferentEmails` to the Generic OAuth Plugin, so providers that doesn't provide the email can be added and also accounts with different emails can be linked as well, similar to the built-in social providers.
Closes #1479.
> fix: support `allowDifferentEmails` on Generic OAuth Plugin

- docs/content/docs/concepts/cookies.mdx
- docs/content/docs/reference/security.mdx
docs/concepts/cookies:
- updated the `Cross Subdomain Cookies` section  with missing details and additional information to make subdomain cookies work
docs/reference/security:
- updated the `Cookies` section with corrected attribute and option names
> corrected, updated cross subdomain cookies docs

- docs/content/docs/authentication/other-social-providers.mdx
The genericOAuth plugin uses ``scopes``, but the docs says ``scope``.
> Fix docs typo in Other Social Providers example

- docs/components/builder/code-tabs/code-editor.tsx
Error shown in the image was occurred when codeEditor component was opened in dev mode :
> Fix React prop spreading warnings in CodeEditor component

- packages/better-auth/src/plugins/email-otp/index.ts
Currently the email OTP plugin saves the user's email address as their "name". This is undesirable as it leads to duplicate data, and also the email address should reasonably be assumed to be private, where as the name can be public.
> Don’t save email address as user name

- packages/better-auth/src/plugins/oidc-provider/index.ts
should be a small change to allow the header `authorization` to be used if body does not contain the client id/secret
refer to https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication
> feat: allow header auth for token ednpoint

- packages/better-auth/src/plugins/index.ts
- packages/better-auth/tsup.config.ts
The captcha plugin is mentioned in [beta](https://beta.better-auth.com/docs/plugins/captcha), but not exported.
> fix: export captcha plugin

- .github/workflows/ci.yml
Cache turbo outputs to massively improve CI times
> chore: cache turbo output to speed up CI

- demo/nextjs/middleware.ts
- docs/content/docs/integrations/next.mdx
in #1528, cookie helper exports were removed from `better-auth` root import and were made only available at `better-auth/cookies`, this PR fixes the imports for the demo and docs
This is somewhat a breaking change for who rely on this export from root and should be mentioned in changelog
> chore: update getSessionCookie import in demo and docs

- packages/better-auth/src/crypto/hash.ts
- packages/better-auth/src/crypto/password.ts
- packages/better-auth/src/plugins/jwt/utils.ts
- packages/better-auth/src/plugins/organization/organization.test.ts
- packages/better-auth/src/plugins/organization/routes/crud-members.ts
- packages/better-auth/src/plugins/passkey/index.ts
- packages/better-auth/src/plugins/two-factor/backup-codes/index.ts
- packages/better-auth/src/social-providers/microsoft-entra-id.ts
- packages/better-auth/src/social-providers/reddit.ts
BetterAuth doesn't work on cloudflare workers without `nodejs_compact` flags due to usage of `Buffer` to do base64 encoding/decoding.
This PR replaces all `Buffer` usage with `base64` from `@better-auth/utils/base64` and `TextEncoder`/`TextDecoder`.
~~There will be a follow up PR to add a cloudflare worker example and test suite to make sure workerd compatibly doesn't break in future.~~
Follow up #1524
fixes #1375
> feat: base64 conversion without Buffer

- .github/workflows/ci.yml
- packages/better-auth/src/plugins/admin/admin.test.ts
The CI jobs doesn't run all Pull requests, thus the Pull's to v1.2 goes without CI.
I ran the tests locally and few of them were failing, I managed to fix the admin ones, but the organization ones are still broken and needs to be investigated
> chore: enable CI for all pull requests

- docs/content/docs/concepts/database.mdx
When using secondary storage, in this case redis the expected session value should be should be proper json but this example doesnt cover that hence getting this error whenever session is used.
>ERROR [Better Auth]: INTERNAL_SERVER_ERROR SyntaxError: "[object Object]" is not valid JSON
> fix(docs) session seconday storage value redis example

- packages/better-auth/src/db/internal-adapter.ts
This PR addresses an issue with the Drizzle adapter where OAuth providers were failing due to incorrect date format handling. The fix removes the .toISOString() call on the Date object when doing verifications cleanup.
Drizzle expects date to be passed as a Date object rather than string.
Error:
```
ERROR [Better Auth]: TypeError: value.toISOString is not a function
```
See more people having this issue on #1035
**Edit -** 
Forgot to add that this bug is only present on v1.2 beta
> fix: oauth failing when using drizzle adapter

- docs/content/docs/authentication/email-password.mdx
- packages/better-auth/src/api/routes/sign-up.ts
- packages/better-auth/src/types/options.ts
This PR brings a new option to the email and password authentication. `disableSignUp` allows disabling the `/sign-up/email` endpoint.
closes https://github.com/better-auth/better-auth/issues/1142
> feat: allow disabling email and password signup

- docs/content/docs/concepts/cookies.mdx
- docs/content/docs/integrations/hono.mdx
Removes the warning below by using partitioned cookies:
<details close>
<summary>raw warnings</summary>
```
Cookie warnings
Cookie "better-auth.session_token" will soon be rejected because it is foreign and does not have the "Partitioned" attribute.
Cookie "better-auth.session_data" will soon be rejected because it is foreign and does not have the "Partitioned" attribute.
```
</details>
I stumbled upon this issue while deploying my frontend web application and backend server to two different domains - repository below:
- https://github.com/nktnet1/rt-stack
1. Deploy apps/web to one domain
2. Deploy apps/server to a different domain using the settings
```ts
advanced: {
defaultCookieAttributes: {
sameSite: "none",
secure: true,
// partitioned: true                 // comment out to produce …
```
> docs: added "partitioned: true" for cross-domain (foreign) cookies

- docs/next.config.mjs
Removed this indicator because it's useless for a fumadocs docs site: (also it's super annoying IMO)
> remove(docs): static route indicator by next

- docs/content/docs/concepts/cookies.mdx
- docs/content/docs/integrations/hono.mdx
Fixes a previous PR where tabs were used instead of spaces for `partitioned: true`
> docs: consistent indents with space instead of tabs

- docs/content/docs/concepts/cli.mdx
Fixes typo `--pacakge-manager`  with `--package-manager` on the CLI documentation.
> docs(fix): typo on cli page

- packages/expo/src/index.ts
The expo handler is trying to pull the location header from the responseHeader key however this key is actually `responseHeaders` plural. This causes a cannot find property on undefined error when trying to use social logins with the expo plugin.
I think this issue is in reference to this:
https://github.com/better-auth/better-auth/issues/1612
> fix: expo plugin accessing wrong key for response headers

- docs/content/docs/concepts/database.mdx
Just a small doc tweak that would have saved me time when learning how the database hooks operate.  Ctx object is available and very useful in these hooks, but not explicitly mentioned in the database hooks docs
> fix(docs): Add reference to `ctx` object for database hooks

- docs/content/docs/plugins/api-key.mdx
> docs(fix): correct typo in api-key documentation

- docs/content/docs/integrations/expo.mdx
I installed a new version of better auth for expo and realized the imports are broken. After digging in the code saw that you no longer build `.js` files, and the `dist` directory structure has changed. But your docs don't reflect these changes.
> fix: update babel config on expo docs

- packages/better-auth/src/social-providers/discord.ts
`display_name` seems to not be present anymore, keeping it in the type just incase im just not seeing it on my own personal discord account
this matches the way next auth handles discord names [here](https://github.com/nextauthjs/next-auth/blob/main/packages/core/src/providers/discord.ts)
> fix: use `global_name` for discord

- docs/content/docs/adapters/drizzle.mdx
This fixes the notation in docs.
I think the correct notation is "drizzleAdapter" instead of "DrizzleAdapter."
https://www.better-auth.com/docs/adapters/drizzle
> docs(fix): Correct typo in drizzle-adapter

- docs/content/docs/authentication/email-password.mdx
- added `resetPasswordTokenExpiresIn` in props table
> docs: update reset password documentation for missing props

- packages/better-auth/src/plugins/admin/admin.ts
- packages/better-auth/src/plugins/admin/call.ts
`ctx.context.adminOptions` is not available because the context is no longer shimmed. The commited changes use `opts` instead.
Also removed unnecessary typings in `adminMiddleware`.
> fix(admin): pass correct options to hasPermission

- packages/stripe/src/index.ts
Fixed an issue where SubtleCryptoProvider cannot be used in a synchronous context in hono by making it async. The issue broke the stripe plugin completely
> (stripe/hono fix): webhook patches for the stripe plugin in hono js

- packages/better-auth/src/plugins/two-factor/backup-codes/index.ts
I noticed that the options parameter was not being passed into the default backup code generation function, which would mean the `length` and `amount` options would never be used. This PR simply fixes that behavior.
> fix(two-factor): Pass options to default backup code generate function

- packages/better-auth/src/plugins/api-key/api-key.test.ts
- packages/better-auth/src/plugins/api-key/routes/create-api-key.ts
- also updated the tests to actually check if the metadata is valid.
read more here: https://discord.com/channels/1288403910284935179/1346739320588992589/1346739320588992589
> fix(api-key): creating API keys metadata always returns null

- packages/better-auth/src/api/routes/update-user.ts
- packages/better-auth/src/db/internal-adapter.ts
Currently, if a user changes his email address to include uppercase letters, he will not be able to verify his email address or reset his password.
Related: https://github.com/RSSNext/Follow/issues/2950
> fix: lowercase email in change email process, find as it is

- docs/components/sidebar-content.tsx
> fix(docs): Polar icon breaking on mobile devices

- docs/content/docs/concepts/email.mdx
The docs mention that there are two ways to initiate email verification, but three ways are listed. I changed the word "two" to "several".
> docs: fix number of triggers

- packages/better-auth/src/plugins/api-key/api-key.test.ts
- packages/better-auth/src/plugins/api-key/routes/verify-api-key.ts
Calling verify endpoint returns the stringified version of the metadata. This is fixed now.
> fix(api-key): Results of `verify` endpoint's metadata isn't parsed

- docs/content/docs/integrations/expo.mdx
This PR addresses a syntax error in the Metro Configuration Section (6) of the Expo integration documentation. The issue was caused by an incorrect file path alias in the `babel.config.js` file, where a missing comma led to invalid JSON syntax. The fix corrects the alias formatting to ensure proper module resolution for the "better-auth" library.
- Updated the `alias` object in `babel.config.js` to include proper comma separation between entries.
- Ensured consistency in the file path aliases for `"better-auth/react"` and `"@better-auth/expo/client"`.
```javascript
alias: {
"better-auth/react": "path/to/node_modules/better-auth/dist/client/react/index.cjs"
"@better-auth/expo/client": "path/to/node_modules/@better-auth/expo/dist/client.cjs",
}
> docs(expo): Fix module-resolver alias configuration

- .github/workflows/preview.yml
- package.json
There's no easy way to test changes made on pull requests by contributors. This PR implements pkg.pr.new, which will publish a preview for every better-auth package on each new commit, providing an easy way to test locally.
See it in action in here:
https://github.com/ThallesP/better-auth/pull/1
> feat: add package previews

- docs/content/docs/plugins/phone-number.mdx
- Fixed `resetPassword` typo
- Added `isOptional` to `phoneNumber` and `phoneNumberVerified`
> fix: docs phone number typo and schema

- docs/content/docs/adapters/drizzle.mdx
- docs/content/docs/adapters/mongo.mdx
- docs/content/docs/adapters/mysql.mdx
- docs/content/docs/adapters/postgresql.mdx
- docs/content/docs/adapters/prisma.mdx
- docs/content/docs/adapters/sqlite.mdx
`generaton` should be `generation`. For example, see here: https://www.better-auth.com/docs/adapters/postgresql#schema-generaton--migration
> fix: Docs typo

- docs/content/docs/plugins/multi-session.mdx
The multiSession.revokeAll() endpoint has been removed and is no longer part of the API.
This fix removes mentions and usage examples from the docs.
> fix(docs): remove references to multiSession.revokeAll() endpoint

- biome.json
- In particular, the browser-extensions example's build folder.
> fix: biome format stack overflow due to `build` outputs

- docs/content/docs/plugins/organization.mdx
- packages/better-auth/src/plugins/organization/organization.test.ts
- packages/better-auth/src/plugins/organization/organization.ts
- packages/better-auth/src/plugins/organization/routes/crud-invites.ts
- packages/better-auth/src/plugins/organization/routes/crud-members.ts
- Added ability to pass multiple roles as array to addMember in addition to string roles
- Changed role type to `InferRolesFromOption<O> | InferRolesFromOption<O>[]` to stop typescript errors when using array with role.
- Add tests to check multiple roles with `addMember` and `inviteMember`
- Updated docs
Breaking Changes: None
> fix(organization): Fix multiple role array not referenced properly

- packages/better-auth/src/api/middlewares/origin-check.test.ts
- packages/better-auth/src/api/middlewares/origin-check.ts
`new URLSearchParams(...).toString()` loves to generate `+`s instead of `%20`s for spaces; this PR allows them in relative paths.
> fix: allow plus signs in relative callback URLs

- packages/better-auth/src/api/routes/email-verification.ts
- packages/better-auth/src/api/routes/session.ts
- packages/better-auth/src/api/routes/sign-in.ts
- packages/better-auth/src/api/routes/update-user.ts
I noticed a bunch of issues when generating a http client using the openapi spec - either wrong return types, required fields or didn't reference the defined models.
> fix: fix issues with openapi types and references

- docs/content/docs/plugins/admin.mdx
Fix docs: Change adminHasPermission method to userHasPermission.
adminHasPermission does not exist.
> [DOCS] Admin plugin: Change adminHasPermission to userHasPermission

- docs/content/docs/contribute/testing.mdx
* Removed the `customConfig` as that's invalid.
* made example code more intuitive.
> fix(docs): contribute/testing docs has incorrect info about test-instance

- docs/content/docs/concepts/database.mdx
This PR updates the `database.mdx` documentation file to fix an issue caused by incorrect handling of JSON data in `secondaryStorage.get`.  
The current documentation suggests using:  
```js
return value ? JSON.stringify(value) : null;
```  
This results in the stored JSON string being re-stringified, causing an issue when parsing it later. Specifically, when `safeJSONParse` is used, it returns a string instead of an array, leading to:  
```
TypeError: list.filter is not a function.
```
The correct approach is to return the value directly instead of wrapping it in `JSON.stringify(value)`. The updated code should be:  
```js
return value ? value : null;
```
- Updated `database.mdx` to reflect the correct implementation.  
- Added a note explaining that `JSON.stringify` should not be used …
> Fix Incorrect JSON Handling in secondaryStorage.get Documentation

- packages/better-auth/src/cookies/index.ts
- packages/better-auth/src/utils/get-request-ip.ts
[Discord thread](https://discord.com/channels/1288403910284935179/1349503864260530209)
This fixes the issue `The \"payload\" argument must be of type object. Received null` where when debugged closer we got an error like this:
It wasn't easy to track down, I had to get better-auth setup in my own codebase and add a bunch of logs at certain areas to determine where this obfuscated `i.get` was coming from. 
Replaces `instanceof Request` check with a more robust `'headers' in req` property check. This change improves reliability by:
1. Avoiding cross-realm issues where `instanceof` can fail when objects are passed between different JavaScript contexts
2. Supporting scenarios with multiple versions of the Request class in the application
3. Following "duck typing" principles - focusing on an …
> fix: access of undefined in runtime that does have great support of instanceof

- packages/better-auth/src/api/routes/sign-in.ts
- packages/better-auth/src/oauth2/create-authorization-url.ts
- packages/better-auth/src/oauth2/types.ts
- packages/better-auth/src/plugins/generic-oauth/index.ts
- packages/better-auth/src/social-providers/apple.ts
- packages/better-auth/src/social-providers/facebook.ts
- packages/better-auth/src/social-providers/github.ts
- packages/better-auth/src/social-providers/gitlab.ts
- packages/better-auth/src/social-providers/google.ts
- packages/better-auth/src/social-providers/linkedin.ts
- packages/better-auth/src/social-providers/microsoft-entra-id.ts
Pass `prompt` and `access_type` into authorization URL while linking accounts using `genericOAuth` plugin. 
fixes #1889
> fix(linking): pass prompt and access_type into authorization URL during account linking

- docs/content/docs/integrations/next.mdx
The import of headers was missing.
> Docs: Fix add import headers

- docs/content/docs/basic-usage.mdx
The basic usage docs say
> Next step: See the [the two factor plugin documentation](https://www.better-auth.com/docs/plugins/2fa).
This PR just removes the repeated `the`.
> Remove repeated word in docs

- docs/content/docs/integrations/remix.mdx
``auth.client.ts`` will trigger code splitting. While this would be fine for the server component (``auth.server.ts``, which needs to stay hidden to end users), putting the authClient in a client only component will force the authClient out of the server bundle. This causes authClient to be undefined during SSR. This makes the integration guide non functional.
Please note that the example you have about Remix is already correctly *not* using ``.client.ts``. 
https://github.com/better-auth/better-auth/blob/main/examples/remix-example/app/lib/auth-client.ts
Read: https://reactrouter.com/explanation/special-files#client-modules
> Remix documentation: Change file name from ``auth.client.ts`` to ``auth-client.ts``

- packages/better-auth/src/api/routes/callback.ts
- packages/better-auth/src/db/schema.ts
- packages/better-auth/src/oauth2/state.ts
- packages/better-auth/src/plugins/admin/admin.ts
- packages/better-auth/src/plugins/api-key/routes/create-api-key.ts
- packages/better-auth/src/plugins/api-key/routes/update-api-key.ts
- packages/better-auth/src/plugins/organization/routes/crud-members.ts
- packages/better-auth/src/plugins/organization/routes/crud-org.ts
- packages/better-auth/src/plugins/organization/schema.ts
- packages/better-auth/src/plugins/two-factor/backup-codes/index.ts
Currently if you have a numeric user ID in your database, Better Auth mostly works, but it fails when encountering Zod schema validation. For example, when linking a social account, Zod is expecting a string for the existing user ID instead of a potential number.
To fix this I've made the Zod schema coerce ids to a string, so if they are represented as numbers in the database, they will always be transformed to strings internally.
Should close #998
> fix: support numeric user IDs

- docs/content/docs/plugins/admin.mdx
This PR fixes an incorrect code example in the admin plugin docs. There is an import name conflict of the `admin` plugin and the `admin` role
> docs(fix): import name conflict in admin plugin roles example

- packages/cli/src/generators/auth-config.ts
This fixes the typo for the use `DrizzleAdapter` to `drizzleAdapter` causing errors after running the new init command.
> cli(fix): Correct typo in auth-config for DrizzleAdapter

- packages/better-auth/src/api/routes/account.ts
A recent change left a variable behind which means an extra DB call
https://github.com/better-auth/better-auth/commit/4ba4ade32b17148c70e4e86eb74a25862195ade0
> remove dead code

- packages/better-auth/src/api/routes/forget-password.ts
Hey,
This PR will help for dbhooks, since right now if a dbhook returns an error (for example a validation error), the verification token will be already removed.
Thanks for great lib 😄
> fix: only delete verification token after succesful db query

- docs/content/docs/plugins/oauth-proxy.mdx
This option is currently missing from the docs. For reference, here's [the relevant code](https://github.com/better-auth/better-auth/blob/fb312ce10b42165d219c2b63673a80dc6ed0d383/packages/better-auth/src/plugins/oauth-proxy/index.ts#L164).
> docs: Add productionURL to OAuth Proxy options

- packages/better-auth/src/index.ts
close #2018
I got this when I built the type from the server code
It indeed uses OAuth2Tokens as the return type.
So I use the same method to fix it.
> fix: type error

- docs/content/docs/guides/supabase-migration-guide.mdx
Node defaults types for environment variables to`string | undefined`. Adding the non-null assertion operator.
> fix(docs): supabase-migration-guide.mdx types

- packages/better-auth/src/plugins/organization/routes/crud-invites.ts
- packages/better-auth/src/plugins/organization/routes/crud-members.ts
- packages/better-auth/src/plugins/organization/schema.ts
Rename `InferRolesFromOption` type to `InferOrganizationRolesFromOption` in organization plugin to avoid any confusion and possible export conflicts
> feat(organization): Rename `InferRolesFromOption` to `InferOrganizationRolesFromOption`

- docs/components/builder/sign-up.tsx
The password fields was missing type="password", so it showed plain text. This PR fixes that.
> Fix: Ensure password confirmation field has type='password'

- packages/better-auth/src/social-providers/vk.ts
It will allow to map profile in VK social-network provider like it already implemented in [kick](https://github.com/better-auth/better-auth/blob/94d2d0544a9e86998444911bef88abca196069a5/packages/better-auth/src/social-providers/kick.ts#L78)
Example:
```typescript
export const auth = betterAuth({
socialProviders: {
vk: {
clientId: process.env.VK_CLIENT_ID!, 
clientSecret: process.env.VK_CLIENT_SECRET!, 
mapProfileToUser: (profile) => {
return {
id: profile.user.user_id,
firstName: profile.user.first_name,
lastName: profile.user.last_name,
middleName: profile.user.middle_name,
email: profile.user.email,
emailVerified: !!profile.user.email,
image: profile.user.avatar,
birthday: profile.user.birthday,
sex: profile.user.sex,
};
},
},
},
});
```
> feat: add mapProfileToUser in vk

- packages/stripe/src/schema.ts
- packages/stripe/src/types.ts
This was documented in docs at https://www.better-auth.com/docs/plugins/stripe#customizing-the-schema but wasn't implemented. This is now fixed.
> fix(stripe): Allow customizing subscription schema

- packages/better-auth/src/social-providers/github.ts
Currently if a user signs up with GitHub and has an email address on their profile, the check for verified emails is skipped. This ensures the check always runs.
> fix: verify github email when profile has an email

- packages/better-auth/src/db/internal-adapter.ts
- packages/better-auth/src/plugins/admin/admin.test.ts
- packages/better-auth/src/plugins/admin/admin.ts
- Fixed the total in admin.listUsers to return the correct total after using the where clause
- Changed internalAdapter.countTotalUsers function to accept an optional where clause
- Added test
closes #2108
> fix(admin): Fix total in listUsers not using where clause

- docs/content/docs/concepts/client.mdx
This pull request includes a small change to the `docs/content/docs/concepts/client.mdx` file. The change corrects spacing in the example codes to ensure proper syntax.
> docs: fix syntax spacing

- docs/content/docs/concepts/rate-limit.mdx
The field `key` shouldn't be the primary key, only `id`.
> fix(docs): rate-limit schema has two primary keys

- packages/better-auth/src/plugins/organization/schema.ts
Fixes incorrect `teamId` inferrence in `InferMember` and `InferInvitation`, where `teamId` was being inferred on type when teams where not enabled and omitted when teams were enabled
> fix(organization): fix inverted teamId inference in conditional types

- packages/better-auth/src/oauth2/refresh-access-token.ts
- packages/better-auth/src/oauth2/utils.ts
- packages/better-auth/src/oauth2/validate-authorization-code.ts
Hi, I found that I always encounter errors when using genericOAuth:
```
{
error: 'invalid_client',
error_description: 'Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method).',
status: 401,
statusText: 'Unauthorized'
}
```
My client_secret contained characters like '+' '=' which didn't seem to be escaped correctly, so I created this PR to fix the issue
> fix(oauth2): encode clientId and clientSecret in authorization header

- packages/better-auth/src/plugins/generic-oauth/index.ts
I noticed that oauth flow for `oauth2.link` is defaulting to the wrong redirect uri. 
Given the base url is ` https://www.example.com` and a generic oauth plugin config like:
```
{
providerId: "slack",
clientId: env.SLACK_CLIENT_ID,
clientSecret: env.SLACK_CLIENT_SECRET,
discoveryUrl: "https://slack.com/.well-known/openid-configuration",
scopes: ["openid", "email", "profile"]
}
```
I would expect that `oauth2.link` redirects to `https://www.example.com/api/auth/oauth2/callback/slack`. 
I'm seeing an incorrect redirect to `https://www.example.com/api/auth/oauth2/callback`. Looking at the code this is becuase we've hardcoded that as the default.
NOTE: This is only an issue for generic oauth linking. `signIn.oauth2` correctly includes the provider id at the end of the redirect URI.
> fix: genericOAuth default redirectURI for account linking

- packages/better-auth/src/utils/get-request-ip.ts
This pull request includes a small but important change to the `getIp` function in the `packages/better-auth/src/utils/get-request-ip.ts` file. The change ensures compatibility with different types of request objects by checking if the `headers` object has a `get` method before attempting to call it.
* [`packages/better-auth/src/utils/get-request-ip.ts`](diffhunk://#diff-b386c725fba47b675a264ee1c46a6a31cf037534f1aae2f758cb7fbf1a18300bL29-R29): Modified the `getIp` function to use `headers.get(key)` if the `headers` object has a `get` method, otherwise it falls back to `headers[key]`.
> fix(get-request-ip): improve header value retrieval for IP address extraction

- docs/content/docs/plugins/oauth-proxy.mdx
Noticed a rouge period at the end there.
> Small typo in example syntax fix

- packages/stripe/src/index.ts
If a user uses something like `subscription.upgrade` and pass a `referenceId`, but they never defined a `options.subscription.authorizeReference` then it will throw an error saying unauthorized. (since no function defined, means  it will just return `false` in it's checks)
While this error is valid, it isn't very clear up-front to the developer that it was due to them passing `referenceId`. To them, they're logged in, so it makes no sense why they would get an unauthorized error.
This PR adds a check if they're missing that function, yet passed `referenceId` to throw a bad request, and provide more info in the server logs.
> fix(stripe): Throw err if passed `referenceId` when no `subscription` authorizeReference` is defined

- docs/content/docs/integrations/hono.mdx
This PR is part of a [stack](https://docs.mrge.io/overview), managed by [mrge](https://mrge.io):
* `main` (default branch)
* [#1538: feat(organization): Add dynamic role authorization](https://github.com/better-auth/better-auth/pull/1538)
* **[#2209: docs(hono): add client-side auth (hono RPC) configuration guide](https://github.com/better-auth/better-auth/pull/2209)** ⬅️ Current PR ([View on mrge](https://mrge.io/pr/better-auth/better-auth/pull/2209))
---
Added documentation for configuring the Hono client to properly handle cross-origin authentication requests. This is a common pain point for developers when setting up Better Auth with Hono, especially during local development when the client and server are on different ports.
- Added new "Client-Side Configuration" section to the Hono …
> docs(hono): add client-side auth (hono RPC) configuration guide

- docs/content/docs/integrations/expo.mdx
- packages/expo/package.json
`expo-linking`, `expo-web-browser` and `expo-constants` are required to use the social integrations the expo plugins provide. I imagine it's not been picked up as these are included in the default Expo template and in the example app but other templates do not include these.
I originally added these as peerDependencies however they are not strictly necessary if you are just going to use email password verification so removed them again.
> chore: add instructions to install required expo packages for login with social to docs

- docs/content/docs/plugins/captcha.mdx
- packages/better-auth/src/plugins/captcha/captcha.test.ts
- packages/better-auth/src/plugins/captcha/constants.ts
- packages/better-auth/src/plugins/captcha/error-codes.ts
- packages/better-auth/src/plugins/captcha/index.ts
- packages/better-auth/src/plugins/captcha/types.ts
- packages/better-auth/src/plugins/captcha/utils.ts
- packages/better-auth/src/plugins/captcha/verify-handlers/cloudflare-turnstile.ts
- packages/better-auth/src/plugins/captcha/verify-handlers/h-captcha.ts
- packages/better-auth/src/plugins/captcha/verify-handlers/index.ts
Addresses #1521 partially: reCAPTCHA Enterprise support will come in a later PR.
Main changes:
- support for Google Recaptcha v3 (risk score) + documentation
- support for hCaptcha + documentation
- fixes #1684
Minor changes:
- added the option to forward the user's IP address
- refactor of the error handling, separating error types between external (visible to the end-user) and internal (visible in server logs) and  using `ctx.logger` to log errors.
No breaking changes expected on existing `cloudflare-turnstile` and `google-recaptcha` (v2) providers.
> feat: (captcha plugin) adding support for Google ReCAPTCHA v3 and hCaptcha

- docs/app/community/_components/stats.tsx
This PR addresses an issue with the button hover states in the community stats component. Previously, in light mode, text would change to white on hover, making it difficult to read against the light background.
- Modified the hover text color for all three buttons (Discord, Downloads, Reddit) to ensure proper contrast
- Added separate styling for dark mode using the `dark:` variant
- Maintained existing group hover effects and transitions
This change ensures text remains legible in both light and dark mode, improving overall accessibility and user experience.
[preview1.webm](https://github.com/user-attachments/assets/5fc226be-75de-4126-9219-c9132a37cb6c)
[preview.webm](https://github.com/user-attachments/assets/bb335a10-35e2-4e02-999e-945aec535774)
> feat: update hover style for light mode in community page

- docs/content/docs/guides/next-auth-migration-guide.mdx
The "Example with Prisma" section under the NextAuth migration guide has the "expires" and "expiresAt" column switched. This isn't a huge issue but just a little confusing when implementing the changes.
Assuming we want to map `expires -> expiresAt`, I changed that section and also updated the comments to make it clear that BetterAuth uses `expiresAt`, while the old column name is `expires`.
> fix(docs): Fix prisma column mappings in NextAuth migration guide

- packages/better-auth/src/plugins/api-key/index.ts
- packages/better-auth/src/plugins/api-key/routes/create-api-key.ts
added check for options in create-api-key.ts. 
option rateLimit.enabled was not used.
closes #1886
> fix(api-key): update rateLimitEnabled default to consider options

- docs/content/docs/plugins/jwt.mdx
This pull request includes a small change to the `docs/content/docs/plugins/jwt.mdx` file.
The change modifies the `definePayload` function to destructure the `user` object directly in the function parameter.
> fix(docs): update parameter destructuring in JWT payload example

- docs/content/docs/authentication/facebook.mdx
- packages/better-auth/src/social-providers/facebook.ts
Facebook login for business requires an additional parameter 'config_id` which points to a specific login strategy since the same business app can have different logins for different purposes (personal login, business system user, etc)
I have threaded that param through and added some docs
> add support for business login using config ids

- docs/content/docs/concepts/users-accounts.mdx
- packages/better-auth/src/api/routes/account.test.ts
- packages/better-auth/src/api/routes/account.ts
- packages/better-auth/src/api/routes/callback.ts
- packages/better-auth/src/db/internal-adapter.ts
- packages/better-auth/src/plugins/generic-oauth/index.ts
- Updated documentation to include information on requesting specific scopes when linking social accounts.
- Added a test case to verify that custom scopes are correctly passed to the authorization URL.
- Modified the account linking endpoint to accept additional scopes as an optional parameter.
> feat(socialLink): add support for custom scopes in social account linking

- docs/components/builder/index.tsx
- docs/components/sidebar-content.tsx
- docs/components/techstack-icons.tsx
- docs/content/docs/examples/svelte-kit.mdx
- examples/svelte-kit-example/README.md
Corrected all instances of “Svelte Kit” to “SvelteKit” in documentation for consistency with official branding.
Did not rename svelte-kit to sveltekit in code as it could introduce breaking changes.
> Correct Svelte Kit to SvelteKit

- packages/better-auth/src/adapters/drizzle-adapter/drizzle-adapter.ts
fix drizzle adapter count `undefined`
reference: #1737
close: #1993
> fix(drizzle-adapter): correct count retrieval in the update function

- packages/better-auth/src/plugins/organization/routes/crud-invites.ts
This resolves a bug where, while you can use 
Email@example.com to log into the account email@example.com. Inviting Email@example.com would mean they can not accept the invite. 
This is done by using .tolowercase on both emails before comparing them
> Fix for #2250 : Checking if User is intended recipient of Invite is casesensetive

- packages/better-auth/src/plugins/haveibeenpwned/haveibeenpwned.test.ts
- packages/better-auth/src/plugins/haveibeenpwned/index.ts
In my humble opinion, `THE_PASSWORD_YOU_ENTERED_HAS_BEEN_COMPROMISED_PLEASE_CHOOSE_A_DIFFERENT_PASSWORD` is **not** a valid error code.
Error codes should be short and are not required the be understand by an end user.
This MR changes the error code to `PASSWORD_COMPROMISED`.
> fix(haveIBeenPwned): Meaningful error code

- packages/better-auth/package.json
- pnpm-lock.yaml
This was fixed [here](https://github.com/better-auth/better-auth/commit/f6cad2b6dbf137fa5fa6cb887780adebcb5be5a0) and regressed [here](https://github.com/better-auth/better-auth/commit/f91270260181f6c0fa226d3cf4b37dbd3f79713b).
Keeping the dependency in the one place it's used (better-auth package) might help avoid accidental removal.
Related to https://github.com/better-auth/better-auth/issues/2024
> re-add concurrently dev dependency

- packages/better-auth/src/plugins/passkey/index.ts
Hi! 
This change fixes the YubiKey USB passkey registration flow on mobile devices.
For some reason, registration fails when the `displayName` field is empty. To reproduce the issue, I’ve prepared a demo project with a basic anonymous + passkey setup:
- GitHub repo: [yubikey-better-auth](https://github.com/EugeneDraitsev/yubikey-better-auth)
- Live demo: [yubikey-better-auth.vercel.app](https://yubikey-better-auth.vercel.app/)
Here’s a screen recording showing the issue:
https://github.com/user-attachments/assets/4e2d2798-6a8f-41ee-ab09-737e656fe35a
To work around the problem, I added the following logic to `auth.ts`:
```typescript
hooks: {
after: createAuthMiddleware(async (ctx) => {
if (ctx.path === '/passkey/generate-register-options') {
const result = ctx.context.returned as {
user: { …
```
> fix: add userDisplayName to the generateRegistrationOptions call

- packages/stripe/src/index.ts
Useful for users who want to make a `plans` array containing stripe plans.
Closes:
https://github.com/better-auth/better-auth/issues/2358
> update(stripe): Export `StripePlan` type

- docs/content/docs/plugins/stripe.mdx
This should resolve confusion with errors related to breaking changes that were introduced in the basil api version of stripe.
> [!CAUTION]
> **This PR should not be merged or reverted, if #2316 gets merged!**
If the next (beta) release will take a while to be put out it might make sense to merge this PR in order to have the docs reflect the current state until the next version. Then in #2316 the changes made via this PR needs to be removed.
> fix(docs): make it clear that we use an outdated stripe version

- docs/content/docs/authentication/apple.mdx
I noticed the docs were lacking in regards to apple sign in integration so i wanted to contribute to make sure others have an easier time than me.
I Noticed that step 1 was longer than all other steps in other providers but imo apple makes it harder so it makes sense why.
I also wanted to add a component to create the apple JWT right in the docs. Just like how the secret is created in the instalation part. Is that allowed? I would use crypto to create the jwt. User would insert all the needed details to generate the apple JWT and i would do it in the website directly.
Thank you, this is my first open source contribution so be kind :)
> docs: Add guide for Sign In with Apple

- docs/content/docs/integrations/astro.mdx
By just following the current docs on Astro integration and rate limiting, you would not get a working solution.
This is because Astros request when using node as adapter does not have the `x-forwarded-for` header.
According to the adapter docs https://docs.astro.build/en/reference/adapter-reference/#clientaddress this seems like it's supposed to be responsibility of the node adapter yet it does not do that by default.
Adding this information to the docs enables users to use rate limiting without issues.
> Update astro.mdx with rate limiting information

- docs/content/docs/plugins/passkey.mdx
I fixed the indentation in the first code block and removed duplicated code in the last two.
However, the docs don't provide enough info on how and where `addPasskey` and `signIn.passkey` should be used. Currently these code blocks include the title `auth-client.ts`, but I believe this is incorrect.
> Fix code blocks in "Passkey"

- docs/content/docs/plugins/admin.mdx
This PR adds important clarification to the documentation regarding the need to explicitly export created roles along with their permissions. It also specifies that the array created contains the available permissions for the roles.
While using the library, I noticed the current documentation didn't clearly explain that:
1. Created roles must be explicitly exported
2. The permissions array serves as the foundation for the roles
These details weren't evident for new users like myself, and this clarification will help prevent common confusion during implementation.
- Added text indicating that roles must be explicitly exported
- Clarified that the created array contains the available permissions for roles
> fix: Update admin plugin documentation with code examples and comments

- packages/better-auth/src/oauth2/validate-authorization-code.ts
- packages/better-auth/src/plugins/generic-oauth/generic-oauth.test.ts
- packages/better-auth/src/plugins/generic-oauth/index.ts
Some OAuth2 provider asks headers to be passed on the authorization request.
In my case, I'm using Qonto and I need to pass a specific header for local development when calling any API endpoints (i.e. https://qonto.notion.site/08c9087f738340fc95a3cd61884f7700?v=15c985c4a8ff4d14b3806a6a42d00ecc&p=108734c9484b4e5cb190157e3093c149&pm=s)
API documentation: https://api-doc.qonto.com/docs/business-api/d6e8790ba0d51-token-endpoint
> feat: custom authorization request headers

- docs/content/docs/plugins/api-key.mdx
Better Auth errors with a `KEY_NOT_FOUND` message not just if the key isn't there, but also _if it's shorter than the length set_ (64 by default)
This PR adds a callout to point this out!
(see https://discord.com/channels/1288403910284935179/1366163971270508585)
> docs: add info about defaultKeyLength

- docs/content/docs/plugins/anonymous.mdx
- packages/better-auth/src/plugins/anonymous/anon.test.ts
- packages/better-auth/src/plugins/anonymous/index.ts
In some cases, `name` is unique in the DB, so this allows the dev to configure generating a random name via the plugin config.
If suitable, in the future we can consider customizing `name`  (and maybe `image` too)  straight from the client's `signIn` method- but it's up for debate.
For further context:
https://discord.com/channels/1288403910284935179/1363063581784018974
> feat(anonymous): Custom anonymous names

- packages/better-auth/src/plugins/api-key/api-key.test.ts
- packages/better-auth/src/plugins/api-key/routes/create-api-key.ts
Ensures the `rateLimitEnabled` property in the ApiKey schema accurately reflects the provided input value, prioritizing it over defaults.
I noticed the value in the database was always true, linked issue to dokploy https://github.com/Dokploy/dokploy/issues/1757
> fix(api-key): pass real rateLimitvalue from ctx.body

- packages/better-auth/src/api/routes/forget-password.ts
- packages/better-auth/src/api/routes/update-user.ts
- packages/better-auth/src/oauth2/state.ts
- packages/better-auth/src/plugins/email-otp/index.ts
- packages/better-auth/src/plugins/magic-link/index.ts
- packages/better-auth/src/plugins/oidc-provider/authorize.ts
- packages/better-auth/src/plugins/passkey/index.ts
- packages/better-auth/src/plugins/phone-number/index.ts
- packages/better-auth/src/plugins/two-factor/index.ts
- packages/better-auth/src/plugins/two-factor/otp/index.ts
ctx wasn’t passed down before, so in `config.databaseHooks.verification.create.before = async (verification, ctx) => {}` the `ctx` argument was `undefined` in some cases. Now we forward ctx so the hook can receive it as expected.
> fix: pass context into createVerificationValue

- packages/better-auth/src/client/config.ts
- packages/better-auth/src/client/types.ts
Helpful for situations like this where you need to get the basePath to fetch internal auth API within `getActions` of a client plugin:
> update: `getActions` from client plugins to include `clientOptions` in get user client config

- docs/content/docs/plugins/stripe.mdx
According to https://github.com/better-auth/better-auth/blob/main/packages/stripe/src/types.ts#L30, this key exists.
I also removed the discount wording from the description (without changing the actual key), since it doesn't have to be a discount, but rather a different price created for the yearly billing period. Although since it mostly is cheaper when taking a look at the effective monthly price, it's probably best to keep the key the same.
> fix(docs): add missing `annualDiscountLookupKey` to plan configuration

- packages/better-auth/src/plugins/generic-oauth/index.ts
As of now if I try to create a generic oauth provider by providing a custom `getUserInfo` function, it fails if I also dont provide a url for `userInfoUrl`.
This should not be the case, if the `getUserInfo` is provided it should be called regardless of the url which is unused either way, so It removes the check for the URL and calls the function if available rightaway
> fix: remove userInfoUrl check to allow using custom function without url

- docs/content/docs/authentication/email-password.mdx
This PR fixes a documentation error in the "Email & Password → Usage → Sign Up" section.
Issue: #2572 
✅ What Changed
Updated the max password length mentioned in the password field description from 32 to 128 characters.
Reflects the actual validation constraint used by the system.
📌 Why This Matters
The previous limit (32 characters) was misleading and could cause unnecessary client-side restrictions.
This fix ensures users and developers have accurate information for implementing sign-up forms.
> 🔧 PR: Fix Incorrect Max Password Length in Docs

- docs/content/docs/integrations/next.mdx
spent an embarrassingly long time working to fix this problem until i remembered that RSCs cannot set cookies. should probably be noted in the docs which would then prevent issues like #2434 
noticed there's pr #2451 but that's an actual integration change instead of a docs note.
> fix(docs): add note regarding cookie caching and RSC

- docs/content/docs/plugins/email-otp.mdx
In Latest Version, 
The `maxAttempts` in emailOTP plugin is replaced with `allowedAttempts`
For Example:
plugins: [
emailOTP({
async sendVerificationOTP({ email, otp, type}) {
//Your email login
},
allowedAttempts: 3,
})
]
> Documentation Change. maxAttempts is now replaced with allowedAttempts

- docs/content/docs/plugins/admin.mdx
I discovered what appears to be a missing comma in a snippet in the `/plugins/admin` of the documentation, so I will fix it.
Thank you.
https://www.better-auth.com/docs/plugins/admin
```diff
const users = await authClient.admin.listUsers({
query: {
searchField: "email",
searchOperator: "contains",
searchValue: "@example.com",
limit: 10,
offset: 0,
sortBy: "createdAt",
-       sortDirection: "desc"
+       sortDirection: "desc",
filterField: "role",
filterOperator: "eq",
filterValue: "admin"
}
});
```
> fix(docs): add missing comma in listUsers query parameters

- packages/better-auth/src/api/routes/account.ts
ref https://github.com/better-auth/better-auth/pull/2557#issuecomment-2883594724
removed `SERVER_ONLY` on `getAccessToken` endpoint so that the method is available to client as stated in the docs
> fix: make getAccessToken available to client

- packages/better-auth/src/adapters/create-adapter/index.ts
This will help prevent potential errors, if not existing errors.
> fix(create-adapter): Get default model in `getModelName`

- packages/cli/src/generators/drizzle.ts
When using the drizzle generator it doesn't include quotes for string default types, causing it to generate code that doesn't compile. This regression was introduced with af402dba3a0a00570a80b6401d6dde134ada1262
> fix: missing quotes for drizzle default values

- docs/app/changelogs/[[...slug]]/page.tsx
- docs/app/changelogs/_components/changelog-layout.tsx
- docs/app/changelogs/_components/default-changelog.tsx
- docs/app/community/_components/stats.tsx
- docs/app/v1/page.tsx
- docs/content/docs/guides/browser-extension-guide.mdx
- docs/content/docs/guides/your-first-plugin.mdx
- docs/content/docs/plugins/stripe.mdx
- docs/content/docs/reference/contributing.mdx
- packages/better-auth/README.md
noticed there were some invalid discord invites, `https://discord.com/better-auth`, so while fixing them changed all links to point to `https://discord.gg/better-auth`
> docs: fix discord invite links

- dev/bun/auth.ts
- packages/better-auth/src/plugins/oidc-provider/index.ts
When using the oidc provider. 
if i do not set a consent page, i get an error.
So I added one:
```
consentPage: "/api/auth/consent",
```
Since i didn't really need one, i just did this in the route:
```
app.get("/api/auth/consent", async (req, res) => {
try {
const data = await auth.api.oAuthConsent({
body: { accept: true },
query: req.query,
headers: req.headers,
});
res.redirect(data.redirectURI);
} catch (e) {
console.error(e);
}
});
```
This doesnt even work, because there is a line checking if the verification has a state param, which should be optional. just removing this one check, allows oauthConsent to be accepted. Doesn't make sense to throw an error when consent is required but state is empty?
> fix consent not able to be accepted if state is empty oidcProvider

- packages/better-auth/src/api/routes/account.ts
- packages/better-auth/src/api/routes/sign-in.ts
- packages/better-auth/src/social-providers/index.ts
fixes #2610
ref https://github.com/better-auth/better-auth/pull/2557#issuecomment-2876979264
the endpoints now use the soclal provider list in context so that generic oauth plugin providers are also allowed in token endpoints
> fix: use dynamic list of social providers to allow generic oauth

- packages/better-auth/src/social-providers/apple.ts
> After logging in with apple, the`emailVerified` is always false. It should be read from the profile like Google.
https://github.com/better-auth/better-auth/blob/87b2ffa5620fc1ca534e8d3d2f3859b629b365ce/packages/better-auth/src/social-providers/google.ts#L156
> fix(apple): correctly map email verification status from profile

- packages/better-auth/src/social-providers/twitter.ts
a small change, making sure we use x.com instead of twitter.com for all oauth endpoints.
reference: https://docs.x.com/resources/fundamentals/authentication/oauth-2-0/authorization-code
> fix: used x.com domain for all twitter provider urls

- packages/better-auth/src/api/routes/sign-in.ts
- packages/better-auth/src/plugins/generic-oauth/index.ts
- packages/better-auth/src/plugins/sso/index.ts
Fix the issue where the callbackURL parameter is missing when emailVerified is false using the idToken method for social login.
Fixed: #2729
> fix: Improve the callbackURL parameter for social, oauth, SSO

- packages/better-auth/src/init.ts
Right now, if an invalid trusted origin is passed, it becomes very hard to debug and find the cause of a given endpoint failing.
As far as I've seen, there error can be as undescriptive as:
> dev: # SERVER_ERROR:  TypeError: Cannot read properties of undefined (reading 'includes')
> dev:     at Array.some (<anonymous>)
> dev:  POST /api/auth/sign-up/email 500 in 915ms
This will throw an error stating that a valid trusted origins list is required.
> update(trustedOrigin): Warn if invalid value is passed

- packages/better-auth/src/plugins/oidc-provider/index.ts
When getting custom claims,
for example using the stripe subscriptions handler with the oidcProvider
if i want to do a DB query or redis lookup of the subscription info, it does not work as we are not awaiting the promise here.
> Add async support for custom user info claims

- packages/better-auth/src/api/routes/account.ts
This PR fixes an issue where the token refresh logic incorrectly attempts to refresh access tokens that **do not have an expiration** (`accessTokenExpiresAt` is `null`).
---
This bug is especially noticeable when using **GitHub social login**, as GitHub:
- Does **not** provide a `refreshToken`
- Does **not** return an `accessTokenExpiresAt`
As a result, the system incorrectly tries to refresh the token and throws: 
```
Failed to get a valid access token
```
---
The logic now checks if `accessTokenExpiresAt` exists **before** attempting a refresh, preventing unnecessary and invalid refresh attempts for providers like GitHub.
---
- Token refresh behavior in `getAccessToken`
- Social login providers with long-lived tokens and no refresh support
closes: #2765
> fix(auth): avoid refreshing tokens without expiration

- docs/content/docs/plugins/mcp.mdx
> docs: fix scopes array for mcp plugin oidc

- packages/better-auth/src/client/query.ts
Fixes https://github.com/better-auth/better-auth/issues/2462
Fixes the `useAuthQuery` function in `packages/better-auth/src/client/query.ts` to be compatible with server-side rendering and prevent hydration issues. 
As a result, server always renders with `isPending: true` and keeps the client initialize with `isPending: true` as well. Session fetch only happens after nanostores is mounted on client browser. A small delay is added on browser to prevent immediate `isPending: false` in case session fetch immediately errors and what not. 
- Skipping fetch on the server
- Safe initial fetch on client on nanostores mount
> fix: SSR handling in useAuthQuery to prevent hydration issues

- packages/better-auth/src/social-providers/microsoft-entra-id.ts
This closes #2769 by fixing the token refresh mechanism for Entra ID.
From Microsoft's documentation [here](https://learn.microsoft.com/en-us/graph/auth-v2-user?tabs=http#step-4-use-the-refresh-token-to-renew-an-expired-access-token) we need to include the "scope" parameter when refreshing the access token.
We also need to include the `offline_access` scope when requesting token, which is documented [here](https://learn.microsoft.com/en-us/graph/auth-v2-user?tabs=http#response-body-properties) so I have added that to the default scopes.
> Fix Entra token refresh

- docs/content/docs/authentication/email-password.mdx
I was a bit worried that I had to create logic to handle the callback URL, but it turns out that the `authClient.signUp.email()` method supports it.
> nit(docs): add callback URL property to sign up method

- docs/content/docs/reference/options.mdx
This PR updates the options reference to include the `trustedOrigins` option, which was previously undocumented but necessary for usage.
> docs: add missing trustedOrigins option

- docs/content/docs/plugins/sso.mdx
SSO API redirect URL path is `/sso/callback/:providerId`
https://github.com/better-auth/better-auth/blob/96634ceefd4605761eb183ae8ed3529b9eb1db3e/packages/better-auth/src/plugins/sso/index.ts#L620-L621
> docs: fix SSO redirect URL

- packages/stripe/src/index.ts
fixes #2860. 
an alternative way of doing this that doesnt depend on the `connector: "OR"` pattern that I haven't seen anywhere else in the repo would be updating this line 
https://github.com/better-auth/better-auth/blob/96634ceefd4605761eb183ae8ed3529b9eb1db3e/packages/stripe/src/index.ts#L260
to this: `(subscription) => subscription.id === subscriptionToUpdate?.stripeSubscriptionId,`
> fix(stripe): inconsistency preventing subscription upgrades

- docs/content/docs/integrations/nuxt.mdx
Documentation:
* Add Nuxt integration example
NuxSaaS is a Nuxt.js full-stack SaaS starter kit:
- Nuxt + Vue 3 + TypeScript
- Nuxt UI
- Auth: Better Auth
- PostgreSQL + DrizzleORM
- Payment: Stripe
- Email: Resend
- Built-in Admin Dashboard
- I18n Support
- SEO Ready
- Deploy to Cloudflare Workers or a self-hosted VPS
> docs: add NuxSaaS link as example integration with Nuxt

- docs/content/docs/adapters/drizzle.mdx
This is supposed to clarify the usage of `usePlural` for the Drizzle ORM adapter.
Looking at the docs I was confused, as the example was using both: a `user` field and the `usePlural` option. But together, they don't make sense in a real config.
This change splits these two up.
> docs(drizzle): Clarify option for plural tables

- turbo.json
Currently the format task only exists in the root. This adds that root task to the turbo.json file and places a dependency on it for the format task
> add dependency on root format task in turbo

- docs/content/docs/integrations/elysia.mdx
This PR updates the example code to reflect the deprecation of error in resolve and instead uses status. This aligns with the latest Elysia context structure as seen [here](https://github.com/elysiajs/elysia/blob/7d921a2c90b99a83240b20d01e8673e49e4327fd/src/context.ts#L190).
> fix(docs): replace error with status in elysia example

- packages/better-auth/src/adapters/mongodb-adapter/mongodb-adapter.ts
The MongoDB adapter was using the `res` from the `findOneAndX` operations instead of using `res.value`. This was causing all properties to have `undefined` as their value. This causes a `APIError: Failed to get session` to be thrown when a session is being refreshed once past `updateAge`.
The return value from `findOneAndX` is `Promise<WithId<TSchema> | ModifyResult<TSchema> | null>`.
MongoDB type definitions:
https://github.com/mongodb/node-mongodb-native/blob/main/src/collection.ts#L100
https://github.com/mongodb/node-mongodb-native/blob/main/src/collection.ts#L982
> fix(mongo-adapter): fix incorrect transformation of findOneAndX outputs

- packages/cli/package.json
- pnpm-lock.yaml
Closes #2908 
Adds @babel/core@^7.0.0 as a dependency of @better-auth/cli
> fixes #2908 - cli missing dependency @babel/core

- docs/content/docs/plugins/stripe.mdx
fwiw, I think that making the user pass the `subscriptionId` parameter to make sure that they don't double charge their users is a really bad footgun. imo, it makes a lot more sense to default to updating subscriptions when there is already an active subscription.
needs #2864 to be merged before it actually works
> docs(stripe): document switching plans on a subscription

- packages/stripe/src/index.ts
> fix(stripe): use the stripeSubscriptionId from the fetched subscription instead of the one from the request

- docs/content/docs/plugins/mcp.mdx
- examples/nextjs-mcp/README.md
This PR fixes a small typo in the documentation for the MCP plugin, where auth.api.getMCPSession was incorrectly capitalized.
- Corrected method name to auth.api.getMcpSession in the docs.
Closes #2977
> Correct method name in MCP docs (getMCPSession → getMcpSession)

- docs/content/docs/installation.mdx
The `createAPIFileRoute` method is no longer available in the latest version of TanStack Start. This commit updates the codebase to use the new `createServerFileRoute` method for handling API routes, ensuring compatibility with the latest library version.
See https://tanstack.com/start/latest/docs/framework/react/server-routes
> fix(deps): migrate from createAPIFileRoute to createServerFileRoute (TanStack Start)

- docs/content/docs/authentication/microsoft.mdx
Hi.
Thanks for building better-auth.
This request is a small documentation fix for Microsoft on how to correctly require user account selection. The original requireSelectAccount is only mentioned in docs in the whole codebase, and consequently does nothing. The setting prompt: "select_account" is from OAuth 2.0, and tested to work.
> docs(microsoft): correct how to require account selection

- packages/better-auth/src/adapters/kysely-adapter/test/state.txt
- packages/better-auth/src/adapters/prisma-adapter/test/state.txt
- packages/better-auth/src/api/routes/update-user.test.ts
- packages/better-auth/src/client/path-to-object.ts
- packages/better-auth/src/db/db.test.ts
- packages/better-auth/src/plugins/phone-number/phone-number.test.ts
When there isn't an active session, `null` is returned on the `/get-session` endpoint. This was missing in types.
> fix(get-session): missing `null` type on /get-session

- packages/better-auth/src/api/routes/update-user.ts
The `deleteUser` api route checks if a session is fresh before allowing the delete, but the `freshAge` config value was never converted from seconds to milliseconds.
With the default `freshAge` of 1 day, this means that the delete call session currently expires after 86 seconds.
This bug appears to have been around for a long time. Given how often time checks need to be made against config times, it would probably be better to create a utility function for doing time comparisons instead and refactor all existing time checks to use it.
> Fix delete user fresh age check

- docs/content/docs/authentication/github.mdx
Fixed wrong user email scope name `user.email` and changed to correct one `user:email`. See available scopes here: https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes
> docs: corrected github user email scope name

- packages/better-auth/src/social-providers/github.ts
> fix: use correct refresh token endpoint for github

- docs/content/docs/integrations/next.mdx
Users can skim code without reading the text, and LLMs can read code and miss-understand context correctly.  Our current middleware example only checks for existence of a cookie, and doesn't validate it.
While we do warn users this isn't secure, some users has raised concern in a Github issue saying it's not obvious enough for users who skim.
Also we don't provide examples on how to authenticate users on each route, we only show middleware optimistic check examples.
Closes https://github.com/better-auth/better-auth/pull/3135
> docs(NextJS): Improve middleware example to be more secure

- docs/content/docs/integrations/tanstack.mdx
This PR updates the docs integration page for TanStack Start as it went through a big change recently
These are the changes I made
- `app` folder is now `src`
- API Routes are now Server Routes
- Proper file names and file paths
> Updated TanStack Start documentation

- packages/better-auth/src/adapters/mongodb-adapter/mongodb-adapter.ts
In the past we didn't have mongoDb adapter move over to createAdapter since we've seen users running into issues.
However some time ago I've merged a PR which I believe fixed the issue, and after testing the org plugin with the mongo adapter that uses `createAdapter` I don't see any issues.
> refactor(mongoAdapter): Migrate to createAdapter

- packages/better-auth/src/adapters/create-adapter/index.ts
Fixes https://github.com/better-auth/better-auth/issues/3069#issuecomment-2985270520
> fix(create-adapter): `getModelName` doesn't add plural to custom model names

- packages/better-auth/src/adapters/create-adapter/test/create-adapter.test.ts
Nothing is broken as of now, just adding another test to prevent future bugs
> add: tests for create-adapter to not include an id when generate id is disabled

- packages/better-auth/src/adapters/create-adapter/index.ts
In Better-auth, we do not allow customising IDs, so nothing takes into account of "different ids". However MongoDB requires ids to be different.
The `getDefaultFieldName` fn in the create-adapter doesn't take into account that IDs from Mongo are not the same as the normal `id`. This is a patch fix until proper resolve is implemented.
> fix(create-adapter): doesn't work with mongoAdapter

- packages/better-auth/src/plugins/api-key/api-key.test.ts
- packages/better-auth/src/plugins/api-key/routes/verify-api-key.ts
When an API key is rate-limited, the status should be `TOO_MANY_REQUESTS` not `UNAUTHORIZED`
> fix(api-key): improve error statuses

- packages/better-auth/src/plugins/anonymous/index.ts
Allows the use of async functions with the generateName callback for the anonymous authentication plugin.
Changes:
- Changed generateName type on AnonymousOptions to support returning a promise
- Added await to the options.generateName call in the auth endpoint
> feat(anonymous): Allow async functions for generating names when using the anonymous auth plugin

- packages/better-auth/src/api/middlewares/origin-check.test.ts
- packages/better-auth/src/api/middlewares/origin-check.ts
fix https://github.com/better-auth/better-auth/issues/3154
The changes fix a bug where protocol-specific wildcard patterns like `https://*.example.com` do not work. This happen because there is a missing logic, if protocol is defined in wildcard trusted origins, we should consider entire url, not only the host to be matched.
1. Fixed wildcard matching logic.
2. Added test coverage - New test case validates both positive and negative scenarios for protocol-specific wildcards.
3. Applied fix to both middleware functions - Both originCheckMiddleware and originCheck now handle protocol-specific wildcards correctly.
> fix: protocol-specific wildcard trusted origins does not work

- packages/better-auth/src/plugins/admin/admin.ts
Right now if the user id is faked it still returns `success: true`. This shouldn't be the case, we should return an error if the user id is invalid.
> fix(admin): throw an error if user id in `/remove-user` is invalid

- packages/better-auth/src/integrations/react-start.ts
This PR enables to use the Tanstack Start integration with both the React and the Solid flavor of Tanstack Start.
Previously, the `setCookie` method was imported from `@tanstack/react-start` which is typically not installed in projects using the Solid flavor.
By importing `setCookie` from the core package `@tanstack/start-server-core`, this integration works regardless of whether `@tanstack/react-start` or `@tanstack/solid-start` is used.
The framework-specific packages re-export the`setCookie` method from the core package ([here](https://github.com/TanStack/router/blob/b01a349583d92c9a8e21024bc9dcceb71ab08244/packages/react-start-server/src/index.tsx#L4)) without modification.
> fix: import setCookie from tanstack start core package

- packages/better-auth/src/plugins/username/index.ts
- packages/better-auth/src/plugins/username/username.test.ts
since the username plugin hooks into the `updateUser` endpoint, it's perfectly reasonable for devs to add this field onto a general user/profile/settings update form with other fields. the plugin currently doesn't discriminate between:
1. user sign up
2. user update conflicting with another user
3. user update conflicting with itself
right now if you wanted to keep the username field within your general `updateUser` form, you would need to conditionally remove the `username` property before submission. this pr allows 3 but still blocks 1 and 2
> fix: exclude current user from username update checks

- packages/better-auth/src/social-providers/google.ts
Regarding Google social provider: In order to get `consent` and `select_account` prompt, we need to pass it like "select_account consent". However BA's type definitions only allow for "select_account+consent" - likely because it's the standard?
Anyway this PR will take that `select_account+consent` defined by the user and convert it to the spaced version (`select_account consent`).
> fix(oauth): Google prompt doesn't allow `+`

- docs/content/docs/reference/options.mdx
- packages/better-auth/src/api/routes/sign-in.ts
- packages/better-auth/src/types/options.ts
Made the email sending inside the sign in route explicit, similar to the sign up route.
> feat(signin): make verification sending in sign in route explicit

- docs/app/blog/[[...slug]]/page.tsx
- docs/app/blog/_components/blog-list.tsx
- docs/app/blog/_components/changelog-layout.tsx
- docs/app/blog/_components/default-changelog.tsx
This pull request updates the Discord link across multiple components in the blog section of the documentation. The link has been changed from `https://discord.com/better-auth` to `https://discord.gg/better-auth` to reflect the correct URL.
Updated Discord links:
* `docs/app/blog/[[...slug]]/page.tsx`: Modified the `href` attribute of the `IconLink` component to use the updated Discord URL. ([docs/app/blog/[[...slug]]/page.tsxL106-R106](diffhunk://#diff-cfbda0f576cacf8abe7216deb1c6233c42072fe514cccaa94d8ed3d58d5fab74L106-R106))
* [`docs/app/blog/_components/blog-list.tsx`](diffhunk://#diff-615d3062cf1af946cc9d255d74a6e7de95b93c0f7b07c40d02355bda07ff65f7L43-R43): Updated the `href` attribute of the `IconLink` component to point to the new Discord URL.
* …
> [FIX]: update Discord link to use the correct invite URL in blogs section

- packages/better-auth/src/plugins/username/index.ts
Added `callbackURL` to body validator.
Handling of this option is already present here:
https://github.com/better-auth/better-auth/blob/c749ccf86934a276f4de732a7ada0b71b2f4c782/packages/better-auth/src/plugins/username/index.ts#L160
https://github.com/better-auth/better-auth/blob/b766b22865895f5cdd7dc575b0cc2e023e795740/packages/better-auth/src/api/routes/email-verification.ts#L55
> fix(username): add `callbackURL` option to `signInUsername`

- packages/better-auth/src/plugins/organization/adapter.ts
- packages/better-auth/src/plugins/organization/call.ts
- packages/better-auth/src/plugins/organization/has-permission.ts
- packages/better-auth/src/plugins/organization/organization.ts
- packages/better-auth/src/plugins/organization/routes/crud-invites.ts
- packages/better-auth/src/plugins/organization/routes/crud-members.ts
- packages/better-auth/src/plugins/organization/routes/crud-org.ts
- packages/better-auth/src/plugins/organization/routes/crud-team.ts
- packages/better-auth/src/plugins/organization/schema.ts
- packages/better-auth/src/plugins/organization/types.ts
A circular dependency between files due to have a export of types with the org index itself was confusing TypeScript's type inference, causing it to default to any for your callback parameters. so now export options would work. and this also should applies to other plugin as well.
> fix: org options type export issue 

- packages/better-auth/src/plugins/mcp/index.ts
hey,
I came across an issue while integrating the mcp plugin with hono using version 1.2.9. The resource_metadata hardcodes the localhost:3000 host, see the issue at https://github.com/better-auth/better-auth/issues/2703 .
This PR fixes it, although I had to extend the Auth interface with the `options` property with type of `BetterAuthOptions`, but I think that should work since, the documentation mentions passing the `auth` instance in which should have the options property on it. (see docs at https://www.better-auth.com/docs/plugins/mcp#mcp-session-handling)
Let me know if anything else is needed, I'd be happy to adjust! 🙏
> fix issue with hardcoded baseURL in withMcpAuth

- packages/better-auth/src/cookies/index.ts
With cookie cache enabled, getSession was sporadically returning null and clearing the session data cookie. The problem is [setCookeCache](https://github.com/better-auth/better-auth/blob/2de1cd27f6177de7e18e57391eb1a0c5dc1cdda3/packages/better-auth/src/cookies/index.ts#L124) generates two expiresAt times, once for the session data and another when signing the payload of the cookie, instead of using the same value. When testing, the values were sometimes identical, and other times 1 tick off, which resulted in [getSession](https://github.com/better-auth/better-auth/blob/b98d17720e6fa642090a88bd8c6a0997647a9275/packages/better-auth/src/api/routes/session.ts#L109) sometimes returning null and clearing the cookies. The fix was to generate one expiresAt time so the signature is signing the …
> fix: use same expires at date for cookie session data payload and signature

- .changeset/little-cherries-tickle.md
- packages/better-auth/src/plugins/magic-link/index.ts
- packages/better-auth/src/plugins/magic-link/magic-link.test.ts
The issue occurs when the baseURL has a root pathname ("/"), causing double slashes in URL construction that result in malformed magic link URLs. The fix treats root pathnames as empty strings, preventing the double slash issue and ensuring proper URL construction with the correct host and port information.
closes #3759
> fix: magic link URL construction

- packages/better-auth/src/plugins/admin/admin.ts
This PR fixes the admin plugin, where when the user sessions are listed on the client, `impersonatedBy` field is not suggested by the code editor but the `impersonatedBy` field is clearly available when using `console.log()`.
> fix: impersonatedBy not appearing in client (type fix)

- packages/better-auth/src/crypto/buffer.ts
An early return value will still lead to a timing attack issue
Related: https://github.com/better-auth/utils/pull/12
> fix: constant time compare

- packages/better-auth/src/__snapshots__/init.test.ts.snap
- packages/better-auth/src/api/to-auth-endpoints.test.ts
- packages/better-auth/src/api/to-auth-endpoints.ts
- packages/better-auth/src/utils/logger.ts
DX improvement: show the error stack when the user enables debug log.
Right now, it's pretty hard to trace which module throws the error
Related feedback: https://github.com/better-auth/better-auth/issues/4080#issuecomment-3201743847
> fix: show error stack in debug mode

- docs/app/blog/_components/default-changelog.tsx
- docs/app/changelogs/_components/default-changelog.tsx
This PR fixes the changelogs page incorrect mentions regex.
Previous:
Now:
> fix: changelogs incorrect mentions

- packages/better-auth/src/adapters/create-adapter/index.ts
- packages/better-auth/src/plugins/username/index.ts
> fix: prevent undefined from passed to adapter in username plugin

- docs/content/docs/installation.mdx
> docs: add missing space typo

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- .github/workflows/preview.yml
```shell
WARNING  TURBO_REMOTE_ONLY is deprecated and will be removed in a future major version. Use TURBO_CACHE=remote:rw
WARNING  TURBO_REMOTE_ONLY is deprecated and will be removed in a future major version. Use TURBO_CACHE=remote:rw
```
> ci: migrate turbo cache

- packages/better-auth/src/plugins/open-api/generator.ts
- packages/better-auth/src/plugins/open-api/open-api.test.ts
closes #4485
Fixes OpenAPI schema generation to properly handle nested Zod objects as well ZodOptional after zod upgrade by recursively processing object properties instead of treating them as simple types. This resolves the issue where the idToken field was incorrectly documented as a string instead of an object with nested properties (token, accessToken, refreshToken).
before 
after
> fix: properly generate OpenAPI schema for nested ZodObject and ZodOptional

- packages/better-auth/src/plugins/api-key/schema.ts
When a user is about to be deleted, you run into an SQL error saying that the user has a foreign key relation to an API key, thus preventing the user from being deleted. This PR adds an `onDelete`  effect to ensure the api keys are deleted as users get deleted.
https://discord.com/channels/1288403910284935179/1417382336315654267
> fix(api-key): cascade api keys on user deletion

- packages/better-auth/src/plugins/organization/routes/crud-org.ts
Hi,
My app includes an organization with approximately 6,000 members. We've encountered an issue where the `activeOrganizationId` field is set to `null` after calling `getFullOrganization`. More details can be found in the [Discord thread](https://canary.discord.com/channels/1288403910284935179/1417776115069485208).
The current implementation of `getFullOrganization` only loads the first 100 members, checking if the logged-in user is among them. This approach leads to undefined behavior in organizations with more than 100 members. If the member was not found in the 100 members loaded, it would update their session to clear `activeOrganizationId`.
This issue was especially hard to pinpoint as my app did not call `getFullOrganization` directly, but it was indirectly called by other …
> fix: support for organizations with large member counts

- packages/cli/src/generators/drizzle.ts
- packages/cli/test/__snapshots__/auth-schema-sqlite-number-id.txt
- packages/cli/test/__snapshots__/auth-schema-sqlite-passkey-number-id.txt
- packages/cli/test/__snapshots__/auth-schema-sqlite-passkey.txt
- packages/cli/test/__snapshots__/auth-schema-sqlite.txt
fix: https://github.com/better-auth/better-auth/pull/4889
`.defaultNow()` which is `(cast((julianday('now') - 2440587.5)*86400000 as integer))` was storing timestamp in subsecond precision. 
refers to [implementation](https://github.com/drizzle-team/drizzle-orm/blob/8e8a9e902410ed2068a015d59180b225045dddf1/drizzle-orm/src/sqlite-core/columns/integer.ts#L136), retrieving timestamp will get wrong result.
using `(current_timestamp)` was storing text into integer field, use `(cast(unixepoch('subsecond') * 1000 as integer)` instead. see https://github.com/drizzle-team/drizzle-orm/issues/2810
> fix(cli): timestamp in schema for Drizzle with SQLite

- packages/better-auth/src/plugins/organization/organization.test.ts
- packages/better-auth/src/plugins/organization/routes/crud-org.ts
Organizations can be created or updated with empty name and slug fields
**To Reproduce**
1. Create organization with empty string as slug: `slug: ""`
2. Create organization with empty string as name: `name: ""`
3. Update organization to have empty slug or name
Added validation to name and slug fields in both create and update organization endpoints
> fix(organization): prevent empty name and slug in create/update
