better-auth/better-auth

docs/content/docs/basic-usage.mdx

setp -> step

---

docs/content/docs/basic-usage.mdx

fixed session management typo in docs/content/docs/basic-usage.mdx

fixed session management typo in docs/content/docs/basic-usage.mdx

---

docs/content/docs/installation.mdx

docs: Fix missing coma on installation

---

packages/better-auth/src/integrations/next-js.ts

fix: nextjs integration basepath typo

---

docs/content/docs/plugins/magic-link.mdx

"better-auth/plugin" -> "better-auth/plugins"

docs: fix magic link import

---

packages/better-auth/src/db/db.test.ts
packages/better-auth/src/db/internal-adapter.ts

fix: custom model names

---

docs/content/docs/integrations/svelte-kit.mdx

i just checked out your docs a bit and found this lil' typo :)

chore: typo fix

---

docs/content/docs/integrations/svelte-kit.mdx

I added this file name, because I was confused myself where to put this code and I wanted to clarify it for others.

docs: add a file name

---

docs/content/docs/plugins/organization.mdx

docs: fix typo

---

packages/better-auth/src/integrations/svelte-kit.ts
packages/better-auth/src/utils/base-url.ts

fix: move import to be dynamic

---

docs/content/docs/plugins/anonymous.mdx

Fixed some grammar, clarified a few sections, and made the instructions a bit more consistent. Should be easier to follow now!

improve clarity and fix grammar for anonymous plugin guide

---

docs/app/layout.tsx
docs/components/nav-bar.tsx
docs/components/nav-mobile.tsx

Fixed this issue https://github.com/better-auth/better-auth/issues/64

fixed mobile menu responsiveness, removed unused imports

---

packages/better-auth/package.json
packages/better-auth/src/api/index.ts
packages/better-auth/src/init.ts
packages/better-auth/src/internal-plugins/cross-subdomain/index.ts
packages/better-auth/src/internal-plugins/cross-subdomain/subdomain-cookies.test.ts
packages/better-auth/src/test-utils/test-instance.ts
packages/better-auth/src/types/options.ts

fix: typed cookies, better-test and fix impl

---

packages/better-auth/src/api/routes/sign-up.ts
packages/better-auth/src/api/routes/update-user.ts
packages/better-auth/src/db/internal-adapter.ts
packages/better-auth/src/plugins/anonymous/index.ts
packages/better-auth/src/plugins/passkey/index.ts

refactor: use consistent id length

---

docs/content/docs/installation.mdx

inlcuding => including
differnt => different

docs: typo on the installation tutorial

---

docs/content/docs/integrations/elysia.mdx

This is an integration document for better auth & [elysia](https://elysiajs.com/)

Docs: Elysia integration

---

packages/better-auth/src/api/routes/sign-up.test.ts
packages/better-auth/src/api/routes/sign-up.ts
packages/better-auth/src/plugins/username/index.ts

fix: custom account-fields

---

docs/content/docs/reference/options.mdx
packages/better-auth/src/api/routes/forget-password.test.ts
packages/better-auth/src/api/routes/forget-password.ts
packages/better-auth/src/db/internal-adapter.ts
packages/better-auth/src/init.ts
packages/better-auth/src/plugins/admin/index.ts
packages/better-auth/src/types/options.ts

fix: support creating credential account on forget password

---

packages/better-auth/src/api/routes/callback.ts
packages/better-auth/src/api/routes/sign-in.ts
packages/better-auth/src/oauth2/create-authorization-url.ts
packages/better-auth/src/oauth2/types.ts
packages/better-auth/src/oauth2/utils.ts
packages/better-auth/src/plugins/generic-oauth/index.ts
packages/better-auth/src/social-providers/apple.ts
packages/better-auth/src/social-providers/discord.ts
packages/better-auth/src/social-providers/facebook.ts
packages/better-auth/src/social-providers/github.ts
packages/better-auth/src/social-providers/google.ts
packages/better-auth/src/social-providers/microsoft-entra-id.ts
packages/better-auth/src/social-providers/social.test.ts
packages/better-auth/src/social-providers/spotify.ts
packages/better-auth/src/social-providers/twitch.ts
packages/better-auth/src/social-providers/twitter.ts
packages/better-auth/src/test-utils/test-instance.ts

fix: infer redirect and respect redirect uri

---

docs/content/docs/plugins/jwt.mdx

Fix small mistakes in the JWT plugin docs.

docs: fix typos & oversights

---

docs/content/docs/concepts/database.mdx
packages/better-auth/src/adapters/mongodb-adapter/index.ts

closes #177 
add support for `plural` option on mongo db adapter

feat(adapter): support plural flag for mongo db adapter

---

docs/content/docs/integrations/elysia.mdx

This PR is to update elysia integration document by add information about middleware and fix wrong path in example code
Example repo: https://github.com/yukikwi/elysia-boiler-plate

Docs: Update middleware document for elysia integration and fix wrong path in example code

---

packages/better-auth/src/plugins/magic-link/index.ts
packages/better-auth/src/plugins/organization/organization.ts

fix: magic link should verify user email

---

docs/content/docs/concepts/database.mdx

[FIX] DOCS - typo - Update database.mdx

---

packages/better-auth/src/plugins/admin/index.ts

fix: remove direct user ref from impersonatedBy

---

packages/better-auth/src/__snapshots__/init.test.ts.snap
packages/better-auth/src/adapters/drizzle-adapter/index.ts
packages/better-auth/src/adapters/kysely-adapter/index.ts
packages/better-auth/src/adapters/mongodb-adapter/index.ts
packages/better-auth/src/adapters/prisma-adapter/index.ts
packages/better-auth/src/adapters/test.ts
packages/better-auth/src/db/internal-adapter.ts
packages/better-auth/src/types/adapter.ts

feat: add delete many support for all adapters

---

packages/better-auth/src/adapters/prisma-adapter/index.ts
packages/cli/src/generators/prisma.ts
packages/cli/test/__snapshots__/schema-mongodb.txt
packages/cli/test/generate.test.ts

fix (cli): add mongodb id map and support array type gen for prisma

---

dev/bun/tsconfig.json
packages/better-auth/package.json

chore: add type versions

---

docs/content/docs/concepts/email.mdx

I have adjusted the docs because there was a capitalization error.

Fix typo: corrected capitalization issue.

---

packages/better-auth/src/plugins/organization/adapter.ts
packages/better-auth/src/plugins/organization/organization.ts
packages/better-auth/src/plugins/organization/routes/crud-invites.ts
packages/better-auth/src/plugins/organization/routes/crud-members.ts
packages/better-auth/src/plugins/organization/routes/crud-org.ts
packages/better-auth/src/plugins/two-factor/verify-middleware.ts
packages/better-auth/src/plugins/username/index.ts

fix: all plugins should use table name from ctx

---

docs/content/docs/authentication/email-password.mdx

I have taken the liberty of adapting the documentation for the integration of email and password.

Revise Email and Password integration docs: improved clarity and added new examples

---

docs/content/docs/concepts/database.mdx

fix(docs): update the docs to fix typo

---

demo/nextjs/app/dashboard/user-card.tsx
docs/content/docs/plugins/2fa.mdx
examples/nextjs-example/app/dashboard/user-card.tsx
packages/better-auth/package.json
packages/better-auth/src/plugins/two-factor/client.ts
packages/better-auth/src/plugins/two-factor/index.ts
packages/better-auth/src/plugins/two-factor/otp/index.ts
packages/better-auth/src/plugins/two-factor/totp/index.ts
packages/better-auth/src/plugins/two-factor/two-factor.test.ts
packages/better-auth/src/plugins/two-factor/types.ts
packages/better-auth/src/plugins/two-factor/verify-middleware.ts
pnpm-lock.yaml

feat: require verification before enabling twofactor

---

docs/content/docs/plugins/anonymous.mdx
packages/better-auth/src/plugins/anonymous/anon.test.ts
packages/better-auth/src/plugins/anonymous/index.ts

fix: Anonymous linking

---

packages/better-auth/src/api/routes/forget-password.ts

fix: optionally read token from current url

---

examples/svelte-kit-example/tsconfig.json
packages/better-auth/src/error/index.ts
packages/better-auth/src/init.ts
packages/better-auth/src/integrations/svelte-kit.ts

fix: log on env related errors instead of throw

---

package.json
packages/better-auth/package.json
pnpm-lock.yaml

updated scripts for build, dev and dev:dts

build script update

---

packages/better-auth/package.json
packages/better-auth/src/api/api.test.ts
packages/better-auth/src/api/index.ts
pnpm-lock.yaml

fix: api error headers should have json content type

---

packages/better-auth/src/db/internal-adapter.test.ts
packages/better-auth/src/db/internal-adapter.ts

fix: find session failing on custom userId

---

docs/content/docs/authentication/email-password.mdx

The docs are incorrect here. `signUp.email` does not take in a `dontRememberMe` property.

[docs]: remove `dontRememberMe` from `signUp.email`

---

docs/components/landing/hero.tsx
docs/package.json

https://github.com/user-attachments/assets/249a3888-30f0-44a7-bc38-22cdf9db064a

feat: new animation for the code preview in the landing page

---

demo/nextjs/lib/auth.ts

Update auth.ts remove duplicate https://

---

CONTRIBUTING.md
demo/nextjs/app/features.tsx

Fix typos in `CONTRIBUTING.md` and `demo/nextjs/app/features.tsx`.
* **CONTRIBUTING.md**
- Fix typo "acknowledge" to "acknowledged" in the **Issues** section.
- Fix typo "plant" to "plan" in the **Plugins** section.
- Add space between "started.If" to "started. If" in the **New Core Features** section.
- Fix typo "to the right direction" to "in the right direction" in the **New Core Features** section.
- Fix typo "prefer, you should" to "prefer you to" in the **Security Issues** section.
* **demo/nextjs/app/features.tsx**
- Fix typo "BetterAuth" to "Better Auth" in the `Card` title.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/better-auth/better-auth?shareId=aa5dcf34-44aa-4092-851e-d34fdd2386a4).

Fix typos in various files

---

docs/content/docs/plugins/multi-session.mdx
docs/content/docs/plugins/organization.mdx

docs:fixed typo issue

---

docs/content/docs/reference/options.mdx

fix: booleam typo

---

packages/better-auth/src/plugins/passkey/client.ts

provide an error message when user cancel passkey resolve #373

---

packages/better-auth/src/plugins/phone-number/index.ts

fix: use get temp if provided

---

examples/astro-example/package.json
examples/astro-example/src/auth.ts

fix: astro example

---

packages/better-auth/src/db/internal-adapter.ts
packages/better-auth/src/plugins/email-otp/email-otp.test.ts
packages/better-auth/src/plugins/magic-link/magic-link.test.ts
packages/better-auth/src/plugins/phone-number/phone-number.test.ts

Verify last otp

---

packages/better-auth/src/__snapshots__/init.test.ts.snap
packages/better-auth/src/adapters/prisma-adapter/index.ts
packages/better-auth/src/init.ts
packages/better-auth/src/plugins/two-factor/backup-codes/index.ts
packages/better-auth/src/plugins/two-factor/totp/index.ts
packages/better-auth/src/plugins/two-factor/two-factor.test.ts
packages/better-auth/src/utils/password.ts

fix(two-factor): require password for sensitive endpoints and fix backup code generating errors

---

packages/better-auth/src/adapters/test.ts
packages/better-auth/src/db/utils.ts

fix: only convert fields if they are defined

---

demo/nextjs/app/(auth)/sign-in/page.tsx
demo/nextjs/app/admin/page.tsx
demo/nextjs/app/dashboard/user-card.tsx
demo/nextjs/components/account-swtich.tsx
demo/nextjs/components/logo.tsx
demo/nextjs/lib/auth-client.ts
demo/nextjs/lib/auth.ts
docs/components/sidebar-content.tsx
docs/content/docs/plugins/one-tap.mdx
packages/better-auth/src/api/routes/session.ts
packages/better-auth/src/api/routes/sign-in.ts
packages/better-auth/src/client/plugins/index.ts
packages/better-auth/src/client/types.ts
packages/better-auth/src/db/internal-adapter.ts
packages/better-auth/src/plugins/index.ts
packages/better-auth/src/plugins/one-tap/client.ts
packages/better-auth/src/plugins/one-tap/index.ts
packages/better-auth/src/plugins/organization/routes/crud-org.ts
packages/better-auth/src/plugins/two-factor/index.ts
packages/better-auth/src/plugins/two-factor/totp/index.ts
packages/better-auth/src/utils/boolean.ts

feat: one tap

---

docs/content/docs/concepts/cookies.mdx
docs/content/docs/concepts/database.mdx
docs/content/docs/concepts/email.mdx
docs/content/docs/concepts/rate-limit.mdx

Updated inconsistencies between the concepts documentation and the codebase.

Minor fixes on concepts documentation

---

packages/better-auth/src/api/routes/forget-password.ts

[Fixed Issue 415](https://github.com/better-auth/better-auth/issues/415)
I've added some `redirectError` and `redirectCallback` which are candidates to be injected directly to the `better-call` context and used through all the routes to reduce issues. `redirectError` is also a candidate function for the  implementation of `errorCallbackURL` proposed in [414](https://github.com/better-auth/better-auth/issues/414).
Fixed also the erroneous behaviour of redirection to the embedded error page if `callbackURL` is present, but `token` is missing

Fix Issue 415: Correct forget password redirect

---

packages/better-auth/src/api/routes/sign-in.ts

fix: remove double email validation

---

packages/better-auth/src/adapters/kysely-adapter/dialect.ts

fix: mysql schema generation stack in introspection

---

packages/better-auth/src/plugins/two-factor/index.ts
packages/better-auth/src/plugins/two-factor/verify-middleware.ts

fix: recreate session for 2fa verification

---

packages/better-auth/src/adapters/kysely-adapter/index.ts
packages/better-auth/src/plugins/admin/admin.test.ts
packages/better-auth/src/plugins/admin/index.ts

fix: search and filter on admin plugin

---

demo/nextjs/components/sign-in.tsx
demo/nextjs/lib/auth.ts
docs/content/docs/authentication/twitter.mdx
packages/better-auth/src/__snapshots__/init.test.ts.snap
packages/better-auth/src/api/routes/callback.ts
packages/better-auth/src/db/internal-adapter.ts
packages/better-auth/src/oauth2/types.ts
packages/better-auth/src/oauth2/validate-authorization-code.ts
packages/better-auth/src/social-providers/twitter.ts

fix: twitter provider

---

packages/better-auth/src/social-providers/apple.ts

Apple SignIn with Identity Token: Cannot destructure property 'kid'

---

examples/nextjs-example/package.json
packages/better-auth/src/adapters/kysely-adapter/index.ts
packages/better-auth/src/api/routes/session-api.test.ts
packages/better-auth/src/api/routes/session.ts
packages/better-auth/src/db/get-migration.ts
packages/better-auth/src/db/utils.ts
pnpm-lock.yaml

fix: mysql date conversion

---

packages/better-auth/src/api/routes/email-verification.test.ts
packages/better-auth/src/api/routes/sign-in.ts

Use Correct BaseURL in Verification Email Resend URLs

---

packages/better-auth/src/adapters/drizzle-adapter/drizzle-adapter.ts

fix: drizzle failing to select

---

packages/better-auth/src/api/routes/forget-password.test.ts
packages/better-auth/src/api/routes/forget-password.ts
packages/better-auth/src/plugins/phone-number/phone-number.test.ts
packages/better-auth/src/types/options.ts

fix: reset password email reset token expiration

---

packages/better-auth/src/api/index.ts
packages/better-auth/src/db/get-tables.ts

fix: capture found instead of not found api error

---

docs/content/docs/integrations/astro.mdx

Added the use of Astro locals instead of using the auth server client to get session and user data

docs: new simpler and optimized astro integration implementation

---

packages/better-auth/src/cookies/index.ts

make sure to pass all the options when deleting cookies, especially domain for crossDomainCookies, otherwise the cookies don't get deleted

fix logout

---

docs/content/docs/plugins/oauth-proxy.mdx

Add spaces to make it look better

Make oauth-proxy.mdx look better

---

packages/better-auth/src/plugins/magic-link/index.ts
packages/better-auth/src/plugins/magic-link/magic-link.test.ts

fix: return user and session on magic link verify 

---

packages/better-auth/src/api/call.ts
packages/better-auth/src/api/index.ts
packages/better-auth/src/plugins/admin/admin.test.ts
packages/better-auth/src/plugins/admin/index.ts
packages/better-auth/src/plugins/email-otp/index.ts
packages/better-auth/src/plugins/multi-session/index.ts
packages/better-auth/src/plugins/two-factor/index.ts
packages/better-auth/src/test-utils/test-instance.ts
packages/better-auth/src/types/context.ts
packages/better-auth/src/types/plugins.ts
packages/better-auth/src/utils/plugin-helper.ts

fix: unify hooks between server and client calls

---

packages/better-auth/src/adapters/kysely-adapter/kysely-adapter.ts
packages/better-auth/src/api/routes/forget-password.test.ts
packages/better-auth/src/api/routes/forget-password.ts
packages/better-auth/src/db/get-migration.ts
packages/better-auth/src/db/internal-adapter.ts
packages/better-auth/src/test-utils/test-instance.ts
packages/cli/test/__snapshots__/migrations.sql

fix: migration should use appropriate data type for each db

---

packages/better-auth/src/db/internal-adapter.ts
packages/better-auth/src/plugins/organization/adapter.ts
packages/better-auth/src/plugins/organization/routes/crud-org.ts

fix: set active org on secondary storage and cookie cache

---

docs/content/docs/installation.mdx
docs/content/docs/integrations/next.mdx
packages/better-auth/package.json
packages/cli/package.json
packages/expo/package.json

Please cherry pick, if helpful, thanks!

Small documentation grammar and formatting fixes 

---

demo/nextjs/app/dashboard/user-card.tsx
docs/components/sidebar-content.tsx
packages/cli/package.json
packages/cli/src/utils/get-config.ts
pnpm-lock.yaml

fix: CLI fails on trailing commas when reading `tsconfig`

---

docs/content/docs/integrations/nuxt.mdx

Documentation:
- Add Nuxt integration example
NuxtZzle Template:
- Nuxt 4 
- Better Autth
-  Drizzle
- TailwindCSS
- Nuxt Content
- Nuxt SEO

Add NuxtZzle link as example integration with Nuxt

---

docs/content/docs/plugins/organization.mdx

Update hasPermission to show correct syntax

Fix error in docs

---

docs/content/docs/concepts/database.mdx

docs: show accessTokenExpiresAt, refreshTokenExpiresAt, and scope as optional

---

docs/components/builder/code-tabs/index.tsx
docs/components/builder/sign-in.tsx
docs/components/builder/sign-up.tsx

When exporting from auth builder, with sign up form code specifically, you would get broken code, missing imports, especially with the tailwind classes. This update aims to resolve that. Example below of broken code exported from the current landing page:
`"use client"
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useState } from "react";
import { Loader2 } from "lucide-react";
import { signIn } from "@/lib/auth-client";
export default function SignIn() {
const [email, setEmail] = useState("");
const [password, setPassword] = useState("");
const [loading, setLoading] = useState(false);
return (
<Card …

Fix syntax errors and missing imports with auth form builder.

---

packages/better-auth/src/plugins/passkey/client.ts
packages/better-auth/src/plugins/passkey/index.ts

feat: update passkey

---

docs/content/docs/concepts/session-management.mdx
packages/better-auth/src/plugins/custom-session/custom-session.test.ts

The customSessionClient import was missing.

Docs: add customSessionClient import

---

packages/better-auth/src/db/internal-adapter.ts

In some cases (e.g., using Cloudflare Tiered Cache) secondary storage can be evicted during a session's lifetime, especially for long-lived sessions. After eviction, reads either return `null` or fallback to the database if the `storeSessionInDatabase` setting is enabled. This PR ensures that sessions are re-persisted to secondary storage under the following conditions:
- `secondaryStorage` is configured
- session is not found in secondary storage
- session exists in database (`storeSessionInDatabase` setting is enabled)
This ensures that sessions can be retrieved from secondary storage on subsequent reads or if the session needs to be updated (due to extended expiration time), it can be saved in secondary storage as well.

fix: ensure persistence to secondary storage upon storage eviction

---

packages/better-auth/src/oauth2/link-account.ts

fix: add check if updateAccount input is empty

---

packages/better-auth/src/plugins/passkey/index.ts
packages/better-auth/src/plugins/username/index.ts

fix: passkey verification shouldn't be required

---

packages/better-auth/src/plugins/organization/adapter.ts
packages/better-auth/src/plugins/organization/routes/crud-org.ts

fix: update organization should accept metadata

---

docs/components/builder/index.tsx

Added htmlFor in builder options label to be able to change switch state by clicking on the label

feat(builder): enhance UI and accessibility for auth options

---

packages/better-auth/src/api/routes/update-user.test.ts
packages/better-auth/src/api/routes/update-user.ts
packages/better-auth/src/client/path-to-object.ts

fix: null should unset image

---

packages/better-auth/src/api/routes/update-user.test.ts
packages/better-auth/src/db/field.ts

fix: update user should infer additional fields properly

---

packages/better-auth/src/plugins/admin/admin.test.ts
packages/cli/src/generators/drizzle.ts
packages/cli/src/generators/prisma.ts
packages/cli/test/__snapshots__/schema-mongodb.prisma
packages/cli/test/__snapshots__/schema-mysql.prisma
packages/cli/test/__snapshots__/schema.prisma
packages/cli/test/generate.test.ts

fix (prisma): the prisma schema generator should add @db.text for MySQL and add many to many fields

---

docs/content/docs/plugins/organization.mdx

docs: add example on how to set active org on create session

---

docs/content/docs/plugins/organization.mdx

docs: has permission on organization doesn't require roles

---

packages/better-auth/src/plugins/two-factor/backup-codes/index.ts

fix: Update backup code to use updateMany since userId isn't enforced  to be unique

---

packages/better-auth/src/plugins/email-otp/email-otp.test.ts
packages/better-auth/src/plugins/email-otp/index.ts

fix(email-otp): should validate email input

---

packages/better-auth/src/api/routes/session.ts
packages/better-auth/src/plugins/two-factor/two-factor.test.ts
packages/better-auth/src/plugins/two-factor/verify-middleware.ts

fix(two-factor): failing on backup code verification

---

packages/better-auth/src/oauth2/link-account.ts

fix: update user info during existing user OAuth login

---

docs/content/docs/comparison.mdx

changed from "And there is a high possibility that we cover more features you need. And you can alway extends it using our plugin system." to "And there's a high possibility that we already cover the features you need. Additionally, you can always extend it using our plugin system."

some spelling and grammar error in comparison.mdx i found while going through the doc.

---

packages/better-auth/src/types/api.ts

fix: make sure asResponse is properly inferred in getSession

---

packages/better-auth/src/api/routes/callback.ts
packages/better-auth/src/plugins/generic-oauth/index.ts
packages/better-auth/src/plugins/generic-oauth/oauth2.test.ts

feat(generic-oAuth): allow generic OAuth to use the base OAuth callback

---

docs/app/docs/[[...slug]]/page.tsx
docs/components/sidebar-content.tsx
docs/content/docs/guides/your-first-plugin.mdx

A guide for first time users at creating a plugin.

docs(add): "your first plugin" guide

---

docs/content/docs/concepts/plugins.mdx

- added text which includes "createAuthClient" allowing users to find it by the doc's search functionality.
- Solves `3` for issue https://github.com/better-auth/better-auth/issues/690 about docs improvements.
- added UI which shows file layout for both the `server` and `client` auth instances.

Update: Added more info to the concept/plugins docs

---

docs/content/docs/installation.mdx

This pull request includes a change to the `docs/content/docs/installation.mdx` file to simplify the route handling for authentication in the `Hono` application.
Documentation Update:
* [`docs/content/docs/installation.mdx`](diffhunk://#diff-ba82586ad92db39dbd2ac8217dcbc24d7fb61452e2b1082d5040be08e5424118L296-R296): Consolidated the `GET` and `POST` route handlers into a single handler using the `app.on` method for the `/api/auth/**` endpoint.

docs: Simplify Hono mount handler example

---

docs/content/docs/guides/your-first-plugin.mdx

- Made all `'` changed to `’`.
- Made all important code examples use code highlight.

update(docs): Minor improvements to the `your-first-plugin` guide

---

docs/app/layout.config.tsx
docs/components/nav-mobile.tsx

closes https://github.com/better-auth/better-auth/issues/832

fix: mobile nav now supports `examples`

---

docs/content/docs/concepts/database.mdx

fix(docs): ugly whitespace in example code.

---

demo/nextjs/app/page.tsx
demo/nextjs/lib/auth-client.ts
packages/better-auth/src/client/react/index.ts
packages/better-auth/src/client/solid/index.ts
packages/better-auth/src/client/svelte/index.ts
packages/better-auth/src/client/vanilla.ts
packages/better-auth/src/client/vue/index.ts

fix: session inference breaking on throw:true

---

packages/better-auth/src/api/routes/email-verification.ts
packages/better-auth/src/api/routes/sign-up.ts

fix: incorrectly append query param in verify email

---

docs/components/icons.tsx
docs/components/sidebar-content.tsx
docs/components/techstack-icons.tsx
docs/content/docs/integrations/nitro.mdx

Hello,
This PR adds to the integration section of the docs a "How To" guide on using Better Auth with Nitro & Prisma.
I created a repo today that shows this: https://github.com/BayBreezy/nitrojs-better-auth-prisma

[Docs] Nitro Integration

---

docs/content/docs/plugins/passkey.mdx

- Added section about using conditional UI
- Added section about debugging and use of emulated passkey devices
- Formatting

feat(passkey): Improve docs

---

packages/better-auth/src/api/routes/sign-up.ts
packages/better-auth/src/db/schema.ts
packages/better-auth/src/plugins/username/index.ts
packages/better-auth/src/plugins/username/username.test.ts

fix: convert username to lowercase on signup

---

packages/better-auth/src/api/routes/forget-password.test.ts
packages/better-auth/src/api/routes/forget-password.ts

fix: respect password config on reset password

---

packages/better-auth/src/adapters/prisma-adapter/prisma-adapter.ts
packages/better-auth/src/adapters/prisma-adapter/test/schema.prisma

fix: support prisma strict undefined checks

---

CONTRIBUTING.md
docs/content/docs/installation.mdx

Closes #887 
**Before**
**After**

docs: fix tanstack-start tab

---

docs/content/docs/concepts/users-accounts.mdx

Seen users in Discord getting confused.
Updated the docs accordingly.

update: account table information for `accountId`

---

docs/content/docs/installation.mdx
packages/better-auth/src/plugins/organization/organization.ts
packages/expo/package.json

fix(expo): export type versions

---

packages/better-auth/src/plugins/jwt/index.ts

fix: mark jwt extractable so they can be exported in crypto web api context

---

packages/better-auth/src/plugins/email-otp/index.ts

fix(email-otp): The  flag should also check for null

---

packages/better-auth/src/plugins/jwt/index.ts

fix(jwt): pass session on definePayload callback

---

docs/content/docs/integrations/expo.mdx
examples/expo-example/src/lib/auth-client.ts
packages/expo/src/client.ts

refactor!(expo): make storage required

---

packages/better-auth/src/plugins/bearer/bearer.test.ts
packages/better-auth/src/plugins/bearer/index.ts

fix(bearer): pre-check token signature to ignore if invalid

---

packages/better-auth/src/social-providers/github.ts

refactor(github): always fetch emails in GitHub provider

---

packages/better-auth/src/api/routes/sign-in.ts
packages/better-auth/src/social-providers/index.ts

feat: export available provider types
fix https://github.com/better-auth/better-auth/issues/934

feat: export available provider types

---

packages/better-auth/src/types/options.ts
pnpm-lock.yaml

docs: remove AUTH_URL

---

docs/content/docs/introduction.mdx

Found a few typos on the intro page.
The framework looks very interesting!

fix: typos on introduction page

---

packages/better-auth/src/__snapshots__/init.test.ts.snap
packages/better-auth/src/db/internal-adapter.ts
packages/better-auth/src/oauth2/link-account.ts

fix(social): should find a user based on a provider returned account id

---

docs/components/sidebar-content.tsx
docs/content/docs/plugins/sso.mdx
packages/better-auth/package.json
packages/better-auth/src/client/plugins/index.ts
packages/better-auth/src/oauth2/validate-authorization-code.ts
packages/better-auth/src/plugins/sso/client.ts
packages/better-auth/src/plugins/sso/index.ts
packages/better-auth/src/plugins/sso/sso.test.ts
packages/better-auth/tsup.config.ts

feat: OpenID SSO Provider

---

packages/better-auth/src/plugins/oidc-provider/index.ts

fix: remove oslo dependency 

---

packages/better-auth/src/plugins/generic-oauth/index.ts

fix: generic oAuth plugin overriding social providers

---

docs/content/docs/integrations/next.mdx

docs(next-integration): add example on how to mount the handler for nextjs page router

---

packages/better-auth/src/client/client.test.ts
packages/better-auth/src/client/query.ts

fix: hydration mismatch on `isPending`

---

packages/better-auth/src/plugins/passkey/index.ts

fix: verify passkey should find by credentialID instead of pk

---

packages/better-auth/src/api/routes/update-user.test.ts
packages/better-auth/src/api/routes/update-user.ts

fix: delete user failing when token is passed directly

---

packages/better-auth/src/db/internal-adapter.test.ts
packages/better-auth/src/db/internal-adapter.ts

fix: secondary storage should use the value after hooks have been evaluated

---

packages/better-auth/src/api/routes/sign-in.ts
packages/better-auth/src/plugins/email-otp/email-otp.test.ts
packages/better-auth/src/plugins/email-otp/index.ts

fix(email-otp): reset password should create credential account

---

packages/cli/src/generators/drizzle.ts
packages/cli/test/__snapshots__/auth-schema.txt

fix(drizzle): default to snake-case

---

examples/expo-example/src/lib/auth-client.ts
examples/expo-example/src/lib/auth.ts
packages/better-auth/src/client/react/index.ts
packages/expo/src/client.ts
packages/expo/src/expo.test.ts

fix(expo): local session cache should be scopped

---

packages/better-auth/src/plugins/email-otp/email-otp.test.ts
packages/better-auth/src/plugins/email-otp/index.ts

fix(email-otp): apply user configuration for expiresIn properly

---

packages/better-auth/package.json
packages/better-auth/src/plugins/oidc-provider/index.ts
pnpm-lock.yaml

fix: upgrade better-auth utils and use subtle from better-auth utils

---

packages/better-auth/src/plugins/email-otp/index.ts

fix(email-otp): it shouldn't send email if user doesn't exist on forget password

---

docs/content/docs/concepts/client.mdx

i use `session.data` because `useSession` return object not null

docs: update vue client example

---

docs/content/docs/concepts/database.mdx

* set already return `string, no need double `JSON.stringify`
* value already parsed no need `JSON.parse`
* add `ioredis` alternative
* `delete` to void function

docs: redis information

---

packages/better-auth/src/api/middlewares/origin-check.test.ts
packages/better-auth/src/api/middlewares/origin-check.ts
packages/better-auth/src/api/routes/email-verification.ts
packages/better-auth/src/api/routes/forget-password.ts
packages/better-auth/src/api/routes/update-user.ts
packages/better-auth/src/plugins/magic-link/index.ts
packages/better-auth/src/plugins/oauth-proxy/index.ts

fix: apply origin check selectively

---

docs/content/docs/concepts/users-accounts.mdx
packages/better-auth/src/__snapshots__/init.test.ts.snap
packages/better-auth/src/api/index.ts
packages/better-auth/src/api/routes/account.test.ts
packages/better-auth/src/api/routes/account.ts
packages/better-auth/src/db/internal-adapter.ts
packages/better-auth/src/error/codes.ts

feat: unlink account

---

packages/better-auth/src/api/routes/account.ts

feat: list accounts should include more metadata

---

packages/expo/package.json
pnpm-lock.yaml

This will cause type checking errors

fix: inconsistent better-call version

---

packages/better-auth/src/plugins/email-otp/email-otp.test.ts
packages/better-auth/src/plugins/email-otp/index.ts

fix(email-otp): apply default rate limiting rules

---

packages/better-auth/src/plugins/open-api/generator.ts
packages/expo/src/expo.test.ts

fix: add version for open api schema

---

packages/better-auth/src/plugins/open-api/index.ts

fix: export open api types

---

packages/better-auth/src/utils/logger.ts

fix: pass unformatted logger

---

packages/better-auth/src/integrations/solid-start.ts

fix: solid start handler type error

---

packages/better-auth/src/plugins/passkey/index.ts

fix: use cookie config for passkey

---

packages/better-auth/src/db/internal-adapter.ts

feat: prefer using accountId over email to find OAuth user

---

packages/better-auth/src/plugins/two-factor/index.ts

Added updatedUser to setCookie on both /two-factor/enable and /two-factor/disable
Closes #1104

Added updatedUser to setCookie on both /two-factor/enable and /two-factor/disable

---

docs/content/docs/plugins/oidc-provider.mdx

https://github.com/better-auth/better-auth/blob/main/packages/better-auth/src/plugins/oidc-provider/schema.ts#L4-L6

fix(docs): oidc-provider table name

---

docs/content/docs/authentication/facebook.mdx
packages/better-auth/src/social-providers/facebook.ts

maybe on future need implement dynamic and base on fields return type of `FacebookProfile` but i don't now how )

refactor: add facebook fields options

---

demo/nextjs/tsconfig.json
packages/better-auth/src/api/middlewares/origin-check.test.ts
packages/better-auth/src/api/middlewares/origin-check.ts
packages/better-auth/src/api/routes/account.ts
packages/better-auth/src/api/routes/email-verification.ts
packages/better-auth/src/api/routes/forget-password.ts
packages/better-auth/src/api/routes/sign-in.ts
packages/better-auth/src/api/routes/sign-up.ts
packages/better-auth/src/api/routes/update-user.ts
packages/better-auth/src/client/config.ts
packages/better-auth/src/client/fetch-plugins.ts
packages/better-auth/src/client/plugins/index.ts
packages/better-auth/src/oauth2/state.ts
packages/better-auth/src/plugins/generic-oauth/index.ts
packages/better-auth/src/plugins/oidc-provider/index.ts

fix: remove current url from requests

---

docs/content/docs/concepts/rate-limit.mdx

forgot to update docs to apply #1191 changes

docs: fixed rate limit schema

---

packages/better-auth/src/db/internal-adapter.ts
packages/better-auth/src/types/options.ts

- Corrected secondaryStorage and storeSessionInDatabase behavior to align with expected functionality. 
- Added preserveSessionInDatabase option to retain database session records when deleting sessions from secondaryStorage. 
- Ensures backward compatibility with previous behavior.
close #1171

feat: secondaryStorage and storeSessionInDatabase behavior

---

packages/better-auth/src/db/internal-adapter.test.ts
packages/better-auth/src/init.ts

- Fixed a bug with the way plugin options are merged, which caused incorrect merging of database hooks

Bug: Database hooks merge issue with plugin

---

packages/better-auth/src/plugins/magic-link/index.ts
packages/better-auth/src/plugins/magic-link/magic-link.test.ts

feat(magic-link): support passing name for registration through magic link

---

packages/better-auth/src/client/client.test.ts
packages/better-auth/src/client/vue/index.ts

fix(vue): failing hook type

---

docs/content/docs/plugins/organization.mdx
packages/better-auth/src/plugins/organization/organization.ts
packages/better-auth/src/plugins/organization/routes/crud-org.ts

feat: add organization deletion config

---

docs/content/docs/integrations/expo.mdx
packages/expo/src/index.ts

fix(expo): make expo origin override optional

---

packages/better-auth/src/plugins/organization/client.ts

fix: update list organization atom on update organization

---

docs/app/docs/[[...slug]]/page.tsx

https://github.com/user-attachments/assets/8e15c20f-a159-4732-b68f-b2037308588d

feat(docs): add buttons to navigate to the next/prev docs page

---

docs/components/side-bar.tsx

Clicking on links or buttons which redirect the path doesn't update the sidebar UI.
This PR fixes this.
https://github.com/user-attachments/assets/0738f6a1-dac8-490d-ae1e-c2741f3846df
https://github.com/user-attachments/assets/cdd0b4b3-0d77-4a62-96ad-bd9ecaac5c28
https://github.com/user-attachments/assets/f869d1df-ee84-434d-b599-f0af78abbbf2
https://github.com/user-attachments/assets/d5fd5e84-fbf2-49f3-82d8-a174ba1da62a

fix: sidebar not updating UI when pathname changes

---

docs/app/community/page.tsx

- Updated the text color on the Community page to fix readability issues in light mode. 
- Previously, the text was visible only in dark mode, making it inaccessible for users in light mode. 
- The new update ensures the text is now clearly visible across both themes, improving accessibility and user experience.
- Modified the text color for the Community page.
- Enhanced UI/UX for light mode users.
- Consistent readability across both light and dark themes.

feat: update text color for light mode in community page

---

packages/better-auth/src/api/routes/update-user.ts
packages/better-auth/src/db/internal-adapter.test.ts
packages/better-auth/src/db/internal-adapter.ts
packages/better-auth/src/oauth2/state.ts
packages/better-auth/src/plugins/email-otp/index.ts
packages/better-auth/src/plugins/oidc-provider/index.ts
packages/better-auth/src/plugins/phone-number/index.ts
packages/better-auth/src/types/options.ts

feat: cleanup expired verification data on fetch

---

docs/content/docs/basic-usage.mdx
packages/better-auth/src/api/routes/sign-in.ts
packages/better-auth/src/oauth2/types.ts
packages/better-auth/src/plugins/generic-oauth/index.ts
packages/better-auth/src/plugins/sso/index.ts
packages/better-auth/src/social-providers/apple.ts
packages/better-auth/src/social-providers/discord.ts
packages/better-auth/src/social-providers/dropbox.ts
packages/better-auth/src/social-providers/facebook.ts
packages/better-auth/src/social-providers/github.ts
packages/better-auth/src/social-providers/gitlab.ts
packages/better-auth/src/social-providers/google.ts
packages/better-auth/src/social-providers/linkedin.ts
packages/better-auth/src/social-providers/microsoft-entra-id.ts
packages/better-auth/src/social-providers/reddit.ts
packages/better-auth/src/social-providers/spotify.ts
packages/better-auth/src/social-providers/twitch.ts
packages/better-auth/src/social-providers/twitter.ts

feat: disable default scopes and allow scopes to be passed on request

---

packages/better-auth/src/plugins/organization/routes/crud-invites.ts

Closes https://github.com/better-auth/better-auth/issues/1273

fix: `sendInvitationEmail` use lowercase email

---

docs/content/docs/authentication/microsoft.mdx

Closes #1313 
* Adds into `Microsoft.mdx` the proper redirect/callback url
* Changes Below:

feat(docs): add Microsoft callback url

---

docs/content/docs/guides/optimizing-for-performance.mdx

Add(docs/optimize-for-performnace): table to show recommeneded index fields

---

packages/better-auth/src/utils/json.ts

fix: handle converting date on session parsing from cookie cache

---

docs/content/docs/basic-usage.mdx
docs/content/docs/concepts/client.mdx
packages/better-auth/src/client/query.ts
packages/better-auth/src/client/react/index.ts

feat: add refetch function for all client hooks

---

packages/better-auth/src/init.ts

fix: socialProvider return null if undefined

---

docs/content/docs/concepts/users-accounts.mdx

Fixes the typo on code highlight

fix(docs): code highlight fix

---

docs/app/global.css

a11y: show scrollbar

---

packages/better-auth/src/api/rate-limiter/index.ts

fix(rate-limit): use the passed model name for rate limiter storage

---

docs/content/docs/introduction.mdx

docs(fix): Update introduction.mdx missing space

---

docs/content/docs/authentication/email-password.mdx

add(docs): demo code to set password on the server.

---

packages/better-auth/src/plugins/phone-number/index.ts

feat(phone-number): add reset password functionality with phone number

---

packages/better-auth/src/plugins/admin/index.ts

feat(admin): set user password

---

demo/nextjs/lib/auth-client.ts
docs/content/docs/plugins/organization.mdx
packages/better-auth/src/plugins/organization/organization.test.ts
packages/better-auth/src/plugins/organization/organization.ts
packages/better-auth/src/plugins/organization/routes/crud-members.ts

feat(organization): leave organization

---

docs/app/docs/[[...slug]]/page.tsx

update(docs): first page doesn't show nav buttons to go to prev pg

---

docs/components/blocks/features.tsx

Fixes social sign-on casing of features section to match casing of other features

Fix docs intro casing in features

---

demo/nextjs/components/one-tap.tsx
demo/nextjs/lib/auth-client.ts
demo/nextjs/lib/auth.ts
docs/content/docs/plugins/one-tap.mdx
packages/better-auth/src/auth.ts
packages/better-auth/src/plugins/one-tap/client.ts
packages/better-auth/src/plugins/one-tap/index.ts

address issues raised by #1415 thread including handling jwt verification using jwks, using prompts with exponential back off and doc improvements

feat(one-tap):  improve Google One Tap integration with JWT verification and improved prompt handling

---

packages/better-auth/src/api/routes/session.ts

fix(api): ctx query and config conflict

---

docs/content/docs/integrations/node.mdx

just a very small change to fix a small typo :)

fix(docs): fix typo in node integration intro

---

packages/better-auth/src/db/internal-adapter.ts

fix(db): normalize email to lowercase in change email verification

---

packages/better-auth/src/plugins/passkey/index.ts
packages/better-auth/src/plugins/passkey/passkey.test.ts

fix(passkey): remove client export from the server plugin

---

packages/better-auth/src/api/routes/session.ts
packages/better-auth/src/db/internal-adapter.ts

fix(admin): impersonate user session expiration

---

packages/better-auth/src/plugins/admin/admin.test.ts
packages/better-auth/src/plugins/admin/index.ts

fix(admin): unban should reset expiration date and reason

---

packages/cli/src/utils/get-config.ts

feat(cli): add support for auth.server.ts for better Remix support

---

packages/better-auth/src/plugins/organization/access/statement.ts
packages/better-auth/src/plugins/organization/organization.test.ts
packages/better-auth/src/plugins/organization/routes/crud-members.ts

fix(organizaiton): restrict admins from removing or updating owners or members with creator roles

---

docs/content/docs/integrations/elysia.mdx

Hi, thanks for having Elysia integration in your documentation.
This PR aims to improve and simplify Elysia's integration code with the latest best practices.
Cheers!

doc(elysia): using mount and macro to simplify code

---

docs/components/sidebar-content.tsx
docs/content/docs/integrations/express.mdx

docs(rename): `node` to `express` in integration docs

---

docs/content/docs/concepts/plugins.mdx

Thanks [@perkinsjr](https://github.com/perkinsjr) !

fix(docs): `sessionMiddleware` import path in plugins docs

---

docs/content/docs/plugins/sso.mdx
packages/better-auth/src/plugins/sso/index.ts
packages/better-auth/src/plugins/sso/sso.test.ts

feat(sso): sign in using the providerId

---

docs/content/docs/plugins/2fa.mdx

The documentation was missing a column

Added missing column in 2fa plugin schema documentation

---

docs/content/docs/plugins/email-otp.mdx
packages/better-auth/src/plugins/email-otp/email-otp.test.ts
packages/better-auth/src/plugins/email-otp/index.ts

The idea is to allow more than numbers, to reduce the length and still have a high level of security. This also gives more freedom by defining the letters. Could be hex or something else.
In my concrete need I want to have a string number combination without zero and O or other letters too similar to a number and I want to have a shorter OTP with higher security.

Add option to set a function to generate OTPs

---

packages/better-auth/src/cookies/cookies.test.ts
packages/better-auth/src/cookies/index.ts
packages/better-auth/src/plugins/two-factor/index.ts
packages/better-auth/src/plugins/two-factor/otp/index.ts
packages/better-auth/src/plugins/two-factor/two-factor.test.ts
packages/better-auth/src/plugins/two-factor/verify-middleware.ts

fix(two-factor): should respect `remember me` value when a user logins in with 2fa

---

demo/nextjs/package.json
docs/package.json
packages/better-auth/package.json
packages/better-auth/src/client/config.ts
packages/better-auth/src/client/types.ts
packages/better-auth/src/client/url.test.ts
packages/expo/package.json
pnpm-lock.yaml

feat(client): add `basePath` option on `createAuthClient`

---

packages/better-auth/src/db/get-migration.ts
packages/cli/test/__snapshots__/migrations.sql

Add last semi-colon to the compiled migrations
Fixes https://github.com/better-auth/better-auth/issues/1558

Add last semi-colon to the compiled migrations to support Cloudflare D1 migration

---

packages/better-auth/src/plugins/oidc-provider/authorize.ts
packages/better-auth/src/plugins/oidc-provider/index.ts

fix(oidc): add support for plain PKCE code challenge method and default config param allowPlainCodeChallengeMethod

---

packages/better-auth/src/api/routes/callback.ts
packages/better-auth/src/plugins/generic-oauth/index.ts
packages/better-auth/src/types/options.ts

refactor: improve OAuth callback error handling and add `errorURL` for custom error pages

---

packages/better-auth/package.json
packages/cli/src/commands/init.ts
packages/cli/src/generators/auth-config.ts

- also fixed ts type errors
- also made the CLI display the dependency packages to install

fix(init-cmd): Dependencies do not install if ENVs are skipped

---

docs/components/landing/hero.tsx

- **feat: v1.2 release banner**
- **chore: lint**

feat(docs): v1.2 banner

---

docs/app/changelogs/[[...slug]]/page.tsx
docs/app/changelogs/_components/default-changelog.tsx
docs/app/changelogs/layout.tsx
docs/components/landing/hero.tsx

- **fix: light theme issue**
- **fix: metadata issue**

fix(docs): metadata and theming

---

packages/better-auth/src/social-providers/apple.ts

Updates apple.ts @see doc link

---

docs/content/docs/adapters/prisma.mdx

Bugfix/Fix prisma.mdx

---

docs/content/docs/plugins/organization.mdx

Fixing `organizationDeletion` option example.

docs: fix organizationDeletion example

---

docs/content/docs/integrations/next.mdx

"The client use nano-store" --> "The client uses nano-store"

docs: fix typo in next.mdx

---

docs/app/docs/[[...slug]]/page.tsx

The button now actually brings you to the correct page on GH to edit.

update(docs): "edit on github" now works

---

docs/content/docs/plugins/admin.mdx

should be
https://github.com/better-auth/better-auth/blob/dab0c80384448470447e3ad9562faa16c9747834/packages/better-auth/src/plugins/admin/access/statement.ts#L12

fix(docs): incorrect permissions for admin plugin

---

docs/content/docs/plugins/admin.mdx

fix(docs): admin pagination section formatted wrong

---

packages/better-auth/src/plugins/organization/adapter.ts
packages/better-auth/src/plugins/organization/organization.test.ts
packages/better-auth/src/plugins/organization/routes/crud-org.ts

fix(organization): two members being created when team is enabled

---

docs/content/docs/integrations/expo.mdx

Updated the docs to correct an example usage

docs: update expo.mdx

---

packages/better-auth/src/social-providers/roblox.ts

Read more here:
https://discord.com/channels/1288403910284935179/1288403910284935182/1347083572015661056

fix(roblox-provider): mapProfileToUser doesn't run

---

docs/app/community/_components/stats.tsx

- **fix: link clickable pointer**
- **fix: container height diff**

fix(docs): stat container height and clickable pointer

---

packages/better-auth/src/plugins/multi-session/index.ts

fix(multi-session): use small cased cookie name inside revoke endpoint

---

docs/content/docs/integrations/next.mdx
packages/better-auth/src/cookies/index.ts

Improved the logic in getSessionCookie() to correctly handle secure prefix and added useSecureCookies config.
closes #1487.

fix: getSessionCookie function and improve docs.

---

packages/better-auth/src/auth.ts
packages/better-auth/src/utils/url.ts

use `x-forwarded-host` and `x-forwarded-proto` to get the base url of the server

feat: support reverse proxied base URLs

---

packages/stripe/src/index.ts

- Added multi-tenant support for Stripe subscription management

feat: add support for multi-tenant Stripe subscriptions

---

packages/better-auth/src/plugins/generic-oauth/index.ts

Small PR to add optional basic authentication in generic oauth plugin

add basic auth to generic oauth plugin

---

packages/better-auth/src/plugins/generic-oauth/index.ts

Forgot to add it in 2nd validateAuthorizationCode call, now it actually works

fix(generic-oauth): added basic auth param in oAuth2Callback

---

docs/content/docs/reference/options.mdx
packages/better-auth/src/api/routes/account.test.ts
packages/better-auth/src/api/routes/account.ts
packages/better-auth/src/types/options.ts
packages/expo/tsconfig.json

feat(account): add option to allow unlinking all accounts

---

docs/content/docs/integrations/nitro.mdx

Minor grammar fixes on nitro page

fix(docs): Nitro documentation minor fixes

---

packages/expo/package.json
packages/expo/src/client.ts
pnpm-lock.yaml

fix(expo): better fetch type mismatch causing type error on expo client plugin

---

dev/bun/tsconfig.json
packages/better-auth/build.config.ts
packages/better-auth/src/client/index.ts
packages/better-auth/src/client/react/index.ts
packages/better-auth/src/client/solid/index.ts
packages/better-auth/src/client/svelte/index.ts
packages/better-auth/src/client/vue/index.ts
packages/better-auth/src/plugins/organization/index.ts

fix: typescript cannot be named without reference to error

---

docs/app/docs/layout.tsx
docs/app/global.css
docs/app/layout.config.tsx
docs/components/nav-bar.tsx
docs/components/nav-mobile.tsx
docs/components/side-bar.tsx
docs/components/theme-toggler.tsx
docs/components/ui/fade-in.tsx
docs/components/ui/select.tsx

I'm using BetterAuth for some of my new projects and really love it, the docs is pretty helpful.
I found a few problems about the UI consistency, it's a small complaint but I think it will look a lot better if we can adjust some details:
And I was confused about the double menu buttons when browsing on phone, I think the minimalism design BetterAuth currently uses will suit better with a single trigger:
And also improved the sidebar animation, hope the maintainers love it ;)

Improve Docs Layout consistency

---

docs/content/docs/plugins/api-key.mdx
packages/better-auth/src/plugins/api-key/api-key.test.ts
packages/better-auth/src/plugins/api-key/client.ts
packages/better-auth/src/plugins/api-key/routes/delete-all-expired-api-keys.ts
packages/better-auth/src/plugins/api-key/routes/delete-api-key.ts

closes https://github.com/better-auth/better-auth/issues/1815

fix(api-key): Delete keys on client doesn't work

---

docs/content/docs/installation.mdx

@tanstack/start is now @tanstack/react-start

Fix tanstack-start installation

---

packages/better-auth/src/plugins/username/index.ts

fix: double matcher on username plugin

---

docs/content/docs/installation.mdx
docs/content/docs/reference/options.mdx
packages/better-auth/src/api/index.ts
packages/better-auth/src/api/to-auth-endpoints.test.ts

feat: disabled paths

---

docs/content/docs/integrations/expo.mdx

docs: update expo resolve path

---

packages/better-auth/src/client/config.ts

fix: trigger session refetch on verify email

---

packages/stripe/src/utils.ts

Fix https://github.com/better-auth/better-auth/issues/1942

fix(stripe): allow plan retrieval by annual discount price ID

---

docs/content/docs/installation.mdx

Changed the base app directory for TanStack Start, from ./app to ./src
https://github.com/TanStack/router/discussions/2863#discussioncomment-12458714

docs: Update Tanstack Start app directory

---

docs/content/docs/plugins/oidc-provider.mdx
packages/better-auth/src/plugins/oidc-provider/index.ts
packages/better-auth/src/plugins/oidc-provider/oidc.test.ts
packages/better-auth/src/plugins/oidc-provider/types.ts

feat(oidc): allow passing additional user claims

---

docs/content/docs/concepts/users-accounts.mdx
packages/better-auth/src/api/routes/account.test.ts
packages/better-auth/src/api/routes/account.ts

fix: unlinkAccount should support optional accountId

---

packages/better-auth/src/api/rate-limiter/index.ts

fix(rate-limiter): handle missing IP address in rate limit function

---

packages/better-auth/src/api/rate-limiter/index.ts

fix(rate-limiter): custom rate limiing table name breaking db query

---

packages/better-auth/src/plugins/organization/adapter.ts

fix(organization): membership limit incorrect usage breaks list organizations

---

packages/cli/src/commands/init.ts
packages/cli/src/generators/auth-config.ts

fix(cli): invalid prisma init config

---

docs/content/docs/integrations/expo.mdx

https://github.com/better-auth/better-auth/issues/1715#issuecomment-2745910215
Sorry to create another PR, this PR changes the configuration example to a minimal example that works properly and has been tested in a new project.

docs: full babel config example for expo

---

docs/components/builder/sign-up.tsx

it was not recognising this as react component  ![image](https://github.com/user-attachments/assets/bbcc8d95-e1f0-4f47-8b85-b4819f870f4a)
after adding default to it , the error is fixed

docs : fixed sign-up component of builder

---

docs/content/docs/integrations/tanstack.mdx

This import has changed in newer versions of TanStack Start

fix: import in tanstack.mdx

---

packages/better-auth/src/api/routes/forget-password.ts

fix(api): forget password flow

---

packages/better-auth/src/plugins/two-factor/index.ts

Additional context:
https://discord.com/channels/1288403910284935179/1357348332527423630/1357348332527423630

add(two-factor): Error codes to infer from plugins, and exported err codes

---

packages/better-auth/src/api/routes/session.ts
packages/better-auth/src/plugins/custom-session/custom-session.test.ts
packages/better-auth/src/plugins/custom-session/index.ts

fix(custom-session): custom session failing to set cookies

---

packages/better-auth/src/types/api.ts

fix: missing disableRefresh type in server side getSession

---

packages/better-auth/src/plugins/admin/admin.ts

Additional info:
https://discord.com/channels/1288403910284935179/1357780287571886120/1357780287571886120

fix(admin): defaultRoles, adminRoles + others not applying user config

---

packages/better-auth/src/plugins/admin/client.ts
packages/better-auth/src/plugins/admin/has-permission.ts
packages/better-auth/src/plugins/organization/client.ts
packages/better-auth/src/plugins/organization/organization.test.ts
packages/better-auth/src/plugins/organization/routes/crud-members.ts

closes #2100 
This is my first ever contribution to OSS, so I would appreciate feedback.
This fixes the above mentioned issue and also some other stuff issues I noticed in the updateMemberRole endpoint.

fix(organization): updateMemberRole failing if issuer has multiple roles

---

docs/content/docs/authentication/twitter.mdx
packages/better-auth/src/social-providers/twitter.ts

feat(provider): twitter email support

---

docs/content/docs/concepts/database.mdx
packages/better-auth/src/cookies/index.ts

This PR is part of a [stack](https://docs.mrge.io/overview), managed by [mrge](https://mrge.io):
* `main` (default branch)
* [#1538: feat(organization): Add dynamic role authorization](https://github.com/better-auth/better-auth/pull/1538)
* **[#2208: fix:(docs) Typos in database schema tables](https://github.com/better-auth/better-auth/pull/2208)** ⬅️ Current PR ([View on mrge](https://mrge.io/pr/better-auth/better-auth/pull/2208))
---

fix:(docs) Typos in database schema tables

---

docs/components/sidebar-content.tsx
packages/better-auth/src/api/routes/email-verification.ts
packages/better-auth/src/api/routes/sign-up.test.ts
packages/better-auth/src/api/routes/sign-up.ts
packages/better-auth/src/oauth2/link-account.ts
packages/better-auth/src/plugins/anonymous/index.ts
packages/better-auth/src/plugins/email-otp/index.ts
packages/better-auth/src/plugins/one-tap/index.ts
packages/better-auth/src/plugins/passkey/index.ts
packages/better-auth/src/plugins/phone-number/index.ts
packages/better-auth/src/plugins/two-factor/index.ts
packages/better-auth/src/plugins/two-factor/otp/index.ts
packages/better-auth/src/plugins/two-factor/totp/index.ts
packages/better-auth/src/plugins/two-factor/verify-middleware.ts
packages/better-auth/src/plugins/username/index.ts
packages/expo/package.json

fix: ipAddress and userAgent missing on server authentication

---

docs/content/docs/plugins/jwt.mdx
packages/better-auth/src/plugins/jwt/index.ts
packages/better-auth/src/plugins/jwt/jwt.test.ts

This PR is part of a [stack](https://docs.mrge.io/overview), managed by [mrge](https://mrge.io):
* `main` (default branch)
* [#1538: feat(organization): Add dynamic role authorization](https://github.com/better-auth/better-auth/pull/1538)
* **[#2194: fix(jwt): add sub claim](https://github.com/better-auth/better-auth/pull/2194)** ⬅️ Current PR ([View on mrge](https://mrge.io/pr/better-auth/better-auth/pull/2194))
---

fix(jwt): add sub claim

---

packages/better-auth/src/oauth2/link-account.ts
packages/better-auth/src/oauth2/types.ts
packages/better-auth/src/plugins/generic-oauth/index.ts
packages/better-auth/src/plugins/sso/index.ts

feat(oauth2): override user info on provider sign-in

---

packages/better-auth/src/types/plugins.ts

This PR is part of a [stack](https://docs.mrge.io/overview), managed by [mrge](https://mrge.io):
* `main` (default branch)
* [#1538: feat(organization): Add dynamic role authorization](https://github.com/better-auth/better-auth/pull/1538)
* **[#2195: fix: plugin option middleware type](https://github.com/better-auth/better-auth/pull/2195)** ⬅️ Current PR ([View on mrge](https://mrge.io/pr/better-auth/better-auth/pull/2195))
---

fix: plugin option middleware type

---

packages/better-auth/src/plugins/admin/admin.ts

fix: delete from session table when stopImpersonate called

---

packages/better-auth/src/api/routes/session-api.test.ts
packages/better-auth/src/cookies/index.ts

fix: filter out fields marked with returned: false from session cookie cache

---

packages/better-auth/src/types/options.ts

- Minor correction in comment explaining the after hook of the session.
- No tests needed

minor correction in type doc comments

---

packages/better-auth/src/plugins/admin/admin.ts

fix(admin): 'dontRememberMe' cookie handling during impersonation

---

docs/components/landing/hero.tsx
packages/better-auth/src/plugins/haveibeenpwned/haveibeenpwned.test.ts
packages/better-auth/src/plugins/haveibeenpwned/index.ts

- **feat: error code support for haveibeenpwned**
- **lint**

feat(password): error code support for haveibeenpwned

---

packages/better-auth/src/plugins/generic-oauth/index.ts

Should close https://github.com/better-auth/better-auth/issues/2240

fix: added c.authentication to refresh token

---

packages/stripe/src/client.ts

fix(stripe): force post method for subscription restore

---

docs/content/docs/authentication/zoom.mdx

- [Zoom](https://www.better-auth.com/docs/authentication/zoom#configure-the-provider)

fix(docs): env variable consistency on zoom

---

packages/stripe/src/index.ts

fix(stripe) adding ability to restore cancelled trialing subscriptions

---

packages/better-auth/src/plugins/generic-oauth/index.ts

feat(generic-oauth): support same provider account linking

---

docs/app/global.css
docs/components/side-bar.tsx

fix(docs): removed 1px from headerbar height variable.

---

packages/stripe/package.json
packages/stripe/src/hooks.ts
packages/stripe/src/index.ts
pnpm-lock.yaml

* Updated the `stripe` package from version `^17.7.0` to `^18.0.0` in `packages/stripe/package.json` and `pnpm-lock.yaml` to use the latest features and improvements. [[1]](diffhunk://#diff-2757b5358a7885372a3e494ce4ec980483ceda7522dd1b61eb52e151772ac9e1R47-R50) [[2]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL1669-R1670) [[3]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL18650-R18647)
* Updated `@types/bun` and `bun-types` from version `1.2.9` to `1.2.10` in `pnpm-lock.yaml` to incorporate the latest type definitions. [[1]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL361-R361) [[2]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL10723-R10724) …

feat: migrate to stripe sdk v18.0.0

---

packages/better-auth/package.json

chore: export adapters

---

packages/better-auth/package.json
pnpm-lock.yaml

chore: upgrade kysely

---

packages/better-auth/src/adapters/drizzle-adapter/drizzle-adapter.ts

Further context:
https://discord.com/channels/1288403910284935179/1363790128254029854/1364625069095125135

fix(drizzle-adapter): missing operators

---

docs/content/docs/guides/your-first-plugin.mdx

According the ts description, reference should be references.

Change plugin doc mistake in schema from 'reference' to 'references'

---

docs/content/docs/installation.mdx

docs: Add ExpressJS v5 implementation disclaimer

---

packages/better-auth/src/plugins/generic-oauth/generic-oauth.test.ts
packages/better-auth/src/plugins/generic-oauth/index.ts

fix(generic-oauth): include missing tokens in account linking

---

packages/better-auth/src/plugins/admin/admin.ts

fix: updateAt field on banning/unbanning users

---

packages/cli/src/generators/drizzle.ts
packages/cli/test/__snapshots__/auth-schema.txt

fix: add a default value for generated fields

---

docs/content/docs/installation.mdx

Per https://github.com/better-auth/better-auth/pull/2006

Add fastify integration guide to installation.mdx

---

packages/better-auth/src/plugins/username/index.ts

fix: add export for username error

---

docs/app/layout.tsx
docs/components/logo-context-menu.tsx

- **fix: avoid redirection**
- **lint**
- **fix: toaster styling**

fix: resolve logo assets redirection and toaster styling issues

---

packages/better-auth/src/api/routes/sign-in.ts
packages/better-auth/src/plugins/username/index.ts

fix: remove unnecessary password hashing in error cases

---

packages/better-auth/src/api/routes/email-verification.ts
packages/better-auth/src/api/routes/sign-in.ts
packages/better-auth/src/api/routes/sign-up.ts
packages/better-auth/src/api/routes/update-user.ts
packages/better-auth/src/db/internal-adapter.ts
packages/better-auth/src/oauth2/link-account.ts
packages/better-auth/src/plugins/admin/admin.test.ts
packages/better-auth/src/plugins/admin/admin.ts
packages/better-auth/src/plugins/anonymous/index.ts
packages/better-auth/src/plugins/email-otp/index.ts
packages/better-auth/src/plugins/magic-link/index.ts
packages/better-auth/src/plugins/one-tap/index.ts
packages/better-auth/src/plugins/passkey/index.ts
packages/better-auth/src/plugins/phone-number/index.ts
packages/better-auth/src/plugins/two-factor/index.ts
packages/better-auth/src/plugins/two-factor/otp/index.ts
packages/better-auth/src/plugins/two-factor/totp/index.ts
packages/better-auth/src/plugins/two-factor/verify-two-factor.ts
packages/better-auth/src/plugins/username/index.ts
packages/better-auth/src/types/options.ts

fix(admin): handle redirecting banned users properly 

---

docs/app/community/_components/stats.tsx
docs/lib/utils.ts

- **fix: add support for million in kformatter**
- **lint**

fix: kformatter support for millions

---

docs/content/docs/guides/create-a-db-adapter.mdx
packages/better-auth/src/adapters/create-adapter/index.ts
packages/better-auth/src/types/adapter.ts

Allow providing `id` in the data of a create method if `forceAllowId` is provided as `true` in the create method call.

update(create-adapter): Allow providing `id` in create method

---

packages/better-auth/src/api/middlewares/origin-check.test.ts
packages/better-auth/src/api/middlewares/origin-check.ts

fix: origin check failing when there is  symbol in a query param

---

docs/content/docs/guides/next-auth-migration-guide.mdx

https://next-auth.js.org/getting-started/upgrade-v4#schema-changes

docs: add field mappings for migrating from next-auth v4

---

docs/content/docs/integrations/hono.mdx

Ref: https://www.npmjs.com/package/@hono/client
`@hono/client` is merged into hono core.

docs: Update hono.mdx for update in the hono/client

---

docs/content/docs/plugins/organization.mdx

docs: fix getFullOrganization example to use correct query parameter structure

---

docs/components/sidebar-content.tsx
docs/components/techstack-icons.tsx
docs/content/docs/authentication/apple.mdx
docs/content/docs/authentication/facebook.mdx
docs/content/docs/authentication/google.mdx
docs/content/docs/basic-usage.mdx
docs/content/docs/concepts/database.mdx
docs/content/docs/concepts/session-management.mdx
docs/content/docs/guides/create-a-db-adapter.mdx
docs/content/docs/integrations/expo.mdx
docs/content/docs/plugins/2fa.mdx
docs/content/docs/plugins/api-key.mdx
docs/content/docs/plugins/jwt.mdx
docs/content/docs/plugins/organization.mdx
docs/content/docs/plugins/passkey.mdx
docs/content/docs/plugins/sso.mdx
docs/content/docs/plugins/stripe.mdx
docs/content/docs/reference/options.mdx

I corrected a few more mistakes that I found while reading the docs.

Corrections

---

docs/app/api/og/route.tsx
docs/components/github-stat.tsx
docs/content/docs/concepts/database.mdx
docs/content/docs/plugins/api-key.mdx
examples/nuxt-example/components/ui/chart-area/AreaChart.vue
packages/better-auth/src/adapters/create-adapter/test/create-adapter.test.ts
packages/better-auth/src/init.test.ts
packages/better-auth/src/plugins/api-key/types.ts
packages/better-auth/src/plugins/captcha/captcha.test.ts
packages/better-auth/src/plugins/oidc-provider/authorize.ts
packages/better-auth/src/social-providers/roblox.ts
packages/cli/src/generators/auth-config.ts

fix: typos

---

packages/better-auth/src/plugins/admin/admin.ts

fix(admin): respect cookie prefix for impersonate admin cookies

---

docs/content/docs/plugins/polar.mdx

Add updated docs to new Polar plugin

New Polar plugin docs

---

docs/content/docs/plugins/polar.mdx

Fixes a few Polar documentation issues

Fix minor Polar documentation issues

---

docs/content/docs/guides/browser-extension-guide.mdx
docs/content/docs/integrations/expo.mdx
docs/content/docs/reference/security.mdx

I was about to implement this myself when I saw that it's already supported, just not documented. I added documenttion for it, using AI to be honest. I checked everything and it looked good, but maybe quickly check again :)

specify docs around wildcard domains

---

packages/better-auth/src/init.test.ts
packages/better-auth/src/init.ts

fix: plugin init context should carry modified context from other plugins

---

docs/content/docs/concepts/session-management.mdx

fix: typo in doc - seesion-management

---

docs/content/docs/guides/create-a-db-adapter.mdx

docs: incorrect reference link

---

packages/better-auth/src/api/routes/forget-password.ts

- Return consistent success status for security
- Add user-friendly message for all requests
- Update OpenAPI documentation
Fixfor issue #2777

fix(auth): improve password reset for unregistered emails

---

docs/content/docs/reference/options.mdx
packages/better-auth/src/api/index.ts
packages/better-auth/src/api/to-auth-endpoints.test.ts
packages/better-auth/src/types/options.ts

A much needed option to allow consuming applications to have complete control over the endpoint paths.  This is very useful in cases where specific api structures need to be followed while still being able to leverage better-auth.

feat(customPaths): Provides an option to modify api paths

---

docs/content/docs/integrations/expo.mdx

Improved Expo documentation by:
- Making sure file references are linked to the correct paths 
- Enabling email/password to make examples work 
- Guiding users to create config files 
- Changing naming convention to be the same throughout the file 
- Sorting installation commands
If I made any changes that you don't agree with let me know and I will revert those!

docs: improve Expo documentation

---

packages/cli/src/generators/kysely.ts

fix: empty migration with semi colon

---

demo/nextjs/app/(auth)/forget-password/page.tsx
docs/components/builder/code-tabs/index.tsx
docs/components/builder/index.tsx
docs/components/builder/sign-in.tsx
docs/components/builder/store.ts
docs/content/docs/authentication/email-password.mdx
docs/content/docs/plugins/phone-number.mdx
examples/expo-example/src/app/forget-password.tsx
examples/nuxt-example/lib/auth-client.ts
examples/nuxt-example/pages/forget-password.vue
packages/better-auth/src/api/index.ts
packages/better-auth/src/api/middlewares/origin-check.test.ts
packages/better-auth/src/api/routes/index.ts
packages/better-auth/src/api/routes/reset-password.test.ts
packages/better-auth/src/api/routes/reset-password.ts
packages/better-auth/src/plugins/phone-number/index.ts
packages/better-auth/src/plugins/phone-number/phone-number.test.ts

fix: rename `forgetPassword` APIs to `requestPasswordReset`

---

packages/expo/src/index.ts
packages/stripe/src/index.ts
packages/stripe/src/stripe.test.ts

feat: support stripe seat upgrade

---

packages/better-auth/src/adapters/prisma-adapter/prisma-adapter.ts

fix(adapter): Unknown argument `eq` on OR clause

---

packages/better-auth/src/social-providers/twitter.ts

fix(twitter): update email verification logic in profile mapping

---

packages/cli/src/generators/index.ts

issue is described in https://github.com/better-auth/better-auth/issues/3003

Allow @better-auth/cli to use custom adapter `createSchema` if implemented

---

packages/better-auth/src/api/routes/update-user.test.ts
packages/better-auth/src/db/internal-adapter.ts

fix: propagate a secondary storage updates on updated user

---

packages/better-auth/src/api/routes/email-verification.ts

fix(email-verification): improve email verification logic to check session and user email consistency

---

docs/content/docs/plugins/passkey.mdx

docs(passkey): Fixed signIn passkey props

---

docs/components/builder/index.tsx
packages/better-auth/src/plugins/email-otp/index.ts

fix: auto-verify email on email otp reset password

---

packages/better-auth/src/plugins/anonymous/index.ts

fix: onLinkAccount trigger on phone number verification

---

docs/components/builder/index.tsx
packages/better-auth/src/plugins/jwt/index.ts

fix: expose headers override in jwt plugin

---

packages/better-auth/src/plugins/username/index.ts

```
ERROR [Better Auth]: User not found { username: [Function: p] }
```
```
ERROR [Better Auth]: User not found { username: 'myusername' }
```

fix(username): log the correct username

---

docs/content/docs/plugins/organization.mdx
packages/better-auth/src/plugins/organization/routes/crud-members.ts

Refined the description to clearly convey that the function retrieves member details of the active organization.

docs(organization): update description for getActiveMember function

---

packages/better-auth/src/plugins/phone-number/index.ts
packages/better-auth/src/plugins/phone-number/phone-number.test.ts

fix(phone-number): verification value should be removed after successful password reset

---

packages/better-auth/src/plugins/jwt/index.ts
packages/better-auth/src/plugins/jwt/jwt.test.ts

fix(jwt): Allow to generate JWKS with other algorithm than the default one

---

docs/content/docs/plugins/email-otp.mdx
packages/better-auth/src/plugins/email-otp/email-otp.test.ts
packages/better-auth/src/plugins/email-otp/index.ts

feat(email-otp): support email verification override

---

packages/better-auth/src/plugins/two-factor/otp/index.ts

fix: otp separator mismatch

---

packages/better-auth/src/api/routes/sign-up.ts

Made sure to pass `rememberMe` to `internalAdapter.createSession` and `setSessionCookie` using `rememberMe === false`.

fix(email): add `rememberMe` option to `signUpEmail`

---

CONTRIBUTING.md

This pull request significantly expands and reorganizes the `CONTRIBUTING.md` file to provide a more comprehensive and structured guide for contributors. The changes include the addition of a table of contents, detailed sections on project structure, development guidelines, and component-specific contribution instructions. It also introduces new content on code formatting, testing, and the pull request process.
* Added a **Table of Contents** for easier navigation, covering topics such as the code of conduct, security issues, project structure, and development workflow.
* Expanded the **Development Guidelines** section with principles for contributing, including maintaining a consistent API, type safety, and clear documentation.
* Introduced a detailed **Getting Started** section with …

better contribution guide

---

docs/content/docs/plugins/api-key.mdx
packages/better-auth/src/plugins/api-key/api-key.test.ts
packages/better-auth/src/plugins/api-key/index.ts
packages/better-auth/src/plugins/api-key/routes/create-api-key.ts
packages/better-auth/src/plugins/api-key/routes/index.ts
packages/better-auth/src/plugins/api-key/types.ts

Solves https://discord.com/channels/1288403910284935179/1384635821159612526

feat(api-key): `requireName` to force require name on keys

---

docs/content/docs/plugins/have-i-been-pwned.mdx

closes  #3298

---

packages/cli/src/generators/drizzle.ts
packages/cli/test/__snapshots__/auth-schema-number-id.txt

fix: schema generation when using advanced.databse.useNumberId

---

packages/stripe/src/index.ts

fix: subscription incomplete update

---

packages/better-auth/src/plugins/admin/admin.ts

Additional info:
https://discord.com/channels/1288403910284935179/1367774652063158342/1367935130911637525

fix(admin): Pass `ctx` to user create db hook

---

docs/components/builder/index.tsx
docs/content/docs/concepts/email.mdx
packages/better-auth/src/adapters/kysely-adapter/test/state.txt
packages/better-auth/src/api/routes/email-verification.test.ts
packages/better-auth/src/api/routes/email-verification.ts
packages/better-auth/src/types/options.ts

fix: callback on successfull email verification

---

packages/better-auth/src/plugins/passkey/client.ts

fix(passkey): added success passkey auth promise resolving

---

docs/content/docs/concepts/rate-limit.mdx
packages/better-auth/src/api/rate-limiter/index.ts
packages/better-auth/src/api/rate-limiter/rate-limiter.test.ts
packages/better-auth/src/types/options.ts

feat(rate-limiter): allow disabling custom paths to not be rate limited

---

docs/content/docs/installation.mdx

docs: installation docs to automatic install using `init` cmd

---

packages/better-auth/src/plugins/last-login-method/index.ts
packages/better-auth/src/plugins/last-login-method/last-login-method.test.ts
packages/better-auth/src/social-providers/tiktok.ts

fix: prevent lastLoginMethod plugin from setting cookie on failed auth
